### ISSUE TITLE
Type checker: missing exit checks

### ISSUE THREAD

**Issue by joey-coleman** [overturetool/overture#14]
> The following bug was [originally reported](https://sourceforge.net/p/overture/bugs/14/) on Sourceforge by [nick_battle](https://sourceforge.net/u/nick_battle/profile/), 2009-09-28 11:31:09:

The type checking of statements which handle exceptions (eg. trap) looks for whether the body of the specification covered can in fact throw exceptions, raising an error if not. This search process is limited in VDMJ. In particular, it cannot cross an operation call, assuming that all operations can raise exceptions. This leads to false negatives - not reporting a TC error, when it should.

**Comment by nickbattle** [comment]
This is now much improved in VDMJ and the example above is certainly reporting problems correctly:
```
Parsed 1 module in 0.124 secs. No syntax errors
Error 3241: Body of trap statement does not throw exceptions in 'DEFAULT' (test.vdm) at line 4:9
Error 3241: Body of trap statement does not throw exceptions in 'DEFAULT' (test.vdm) at line 8:9
Type checked 1 module in 0.254 secs. Found 2 type errors
```
Applying the changes to the Overture visitor framework next...

**Comment by nickbattle** [comment]
Now fixed in Overture on ncb/development.

**Comment by nickbattle** [comment]
Added some extra changes that allow expressions to be searched for exit clauses (via their apply calls, which may be operations that raise exceptions).
