### ISSUE TITLE
Fix copyright headers

### ISSUE THREAD

**Issue by joey-coleman** [overturetool/overture#249]
Update the copyright headers and license files

License per module (if module not mentioned then pure Overture:

Fujitsu
- ast
- ctruntime
- interpreter (many files)
- parser -- almost all of it
- combinatorialtesting

Combined Overture and Fujitsu
- ast
- ctruntime
- interpreter
- parser
- pog-string-based
- pog
- typechecker
- combinatorialtesting

**Comment by lausdahl** [comment]
Using Mac remove old license script: 

```
git ls-files **/*.java | xargs -n1 sed -i '' -e '/^package/,$!d'
```

Completed:
code:
- [x] modelchecker
- [x] guibuilder
- [x] prettyprinter
- [x] testframework
- [x] testing
- [x] codegen
- [x] codegen-runtime
- [x] combinatorial testing
- [x] parser
- [x] ast
- [x] type checker
- [ ] interpreter
- [ ] pog
- [x] vdmtools
- [ ] vdmj_compatibility_tests

ide:
- [x] core
- [x] builders
- [x] debug
- [x] help
- [x] parsers
- [x] platform
- [x] product
- [x] tests
- [x] ui
- [x] vdmpp
- [x] vdmrt
- [x] vdmsl
- [x] plugins
  - [x] codegen
  - [x] ct
  - [x] coverageditor
  - [x] csk
  - [x] developerutils
  - [x] externaleditor
  - [x] latex
  - [x] poviewer
  - [x] prob-runtime
  - [x] quickinterpreter
  - [x] rttraceviewer
  - [x] uml2
  - [x] uml2.tests

**Comment by nickbattle** [comment]
This bug has been superseded by https://github.com/overturetool/overture/issues/705.
