### ISSUE TITLE
Type information does not seem to be fully taken into account in POG

### ISSUE THREAD

**Issue by pglvdm** [overturetool/overture#289]
For a VDM-SL model like:
~~~
values
 
  p1:Period = mk_token("Monday day");
  p2:Period = mk_token("Monday night");
  p3:Period = mk_token("Tuesday day");
  p4:Period = mk_token("Tuesday night");
  p5:Period = mk_token("Wednesday day");
  ps : set of Period = {p1,p2,p3,p4,p5};

  eid1:ExpertId = mk_token(134);
  eid2:ExpertId = mk_token(145);
  eid3:ExpertId = mk_token(154);
  eid4:ExpertId = mk_token(165);
  eid5:ExpertId = mk_token(169);
  eid6:ExpertId = mk_token(174);
  eid7:ExpertId = mk_token(181);
  eid8:ExpertId = mk_token(190);
  
  e1:Expert = mk_Expert(eid1,{<Elec>});
  e2:Expert = mk_Expert(eid2,{<Mech>,<Chem>});
  e3:Expert = mk_Expert(eid3,{<Bio>,<Chem>,<Elec>});
  e4:Expert = mk_Expert(eid4,{<Bio>});
  e5:Expert = mk_Expert(eid5,{<Chem>,<Bio>});
  e6:Expert = mk_Expert(eid6,{<Elec>,<Chem>,<Bio>,<Mech>});
  e7:Expert = mk_Expert(eid7,{<Elec>,<Mech>});
  e8:Expert = mk_Expert(eid8,{<Mech>,<Bio>});
  exs : set of Expert = {e1,e2,e3,e4,e5,e6,e7,e8};

  s: map Period to set of Expert
     = {p1 |-> {e7,e5,e1},
        p2 |-> {e6},
        p3 |-> {e1,e3,e8},
        p4 |-> {e6}};

  a1:Alarm = mk_Alarm("Power supply missing",<Elec>);
  a2:Alarm = mk_Alarm("Tank overflow",<Mech>);
  a3:Alarm = mk_Alarm("CO2 detected",<Chem>);
  a4:Alarm = mk_Alarm("Biological attack",<Bio>);
  alarms: set of Alarm = {a1,a2,a3,a4};
  
  plant1 : Plant = mk_Plant(s,{a1,a2,a3})
  
operations

Run: Expert ==> set of Period
Run(e) == return ExpertIsOnDuty(e, plant1);

traces 

  Test1: let a in set alarms
         in
           let p in set ps 
           in
             (NumberOfExperts(p,plant1);
              pre_ExpertToPage(a,p,plant1);
              let ex in set exs
              in
                post_ExpertToPage(a,p,plant1,ex))
               
  Test2: let ex in set exs
         in
           ExpertIsOnDuty(ex,plant1)
 ~~~
PO10 that gets generated states: (inv_Schedule(s) and is_(s, map (Period) to (set of (Expert)))) where I think that it really only needs to be "inv_Schedule(s)" because the type information should be deducable by the type checker directly. So it might not be correctly inserted by the TC.

**Comment by joey-coleman** [comment]
@ldcouto is this bug fixed?

**Comment by ldcouto** [comment]
It is now.

According to @nickbattle , there is some legacy reason for why the `is_` was always generated as part of an invariant type PO though the details have been lost to the mists of time. It may just be that the two parts of the invariant PO were always generated for convenience, regardless of the `is_` being needed or not. 

Regardless, I've added code that checks if the expression already matches the underlying type and, if so, suppresses the generation of the `is_` clause.

**Comment by nickbattle** [comment]
I think the point about the is_ is that the inv_T test itself is not sufficient. That is just a boolean predicate, but to be a member of T, the candidate type must also be a member of the basic type of T (here, nat). So I think the PO is correct, but we should be able to detect that is_(a, nat) is satisfied. It sounds like you've fixed that now.

**Comment by ldcouto** [comment]
Yeah. This is another example of how to divide responsibility between the POG and the (hypothetical) theorem prover.

In theory, these checks are just suppressing trivial proofs so it should not really affect the overall outcome.
