### ISSUE TITLE
Instantiation of Polymorphic function missed by the type checker

### ISSUE THREAD

**Issue by peterwvj** [overturetool/overture#308]
In the spec below it is possible to execute the Run operation resulting in a following run-time error: "Error 3033: Polymorphic function has not been instantiated: f in 'Entry'.."

I think this should be picked up on during type checking.

class Entry

functions

public static f[@A] : @A -> nat
f(s) == 1;

operations

public static Run : () ==> nat
Run () == return f('a');
	
end Entry

**Comment by nickbattle** [comment]
I've been looking at this and have a better solution, so I'll check that in when I can port it over from VDMJ. Probably after Easter.

**Comment by peterwvj** [comment]
@nickbattle can we close this issue?

**Comment by nickbattle** [comment]
Yes, sorry, I did port the change over but I forgot to update this issue. The change is in.

**Comment by peterwvj** [comment]
Great thanks!
