### ISSUE TITLE
R/G Obligation Generator

### ISSUE THREAD

**Issue by ldcouto** [overturetool/overture#344]
Add suport for R/G obligations to the POG.

This is a long project. We'll start with an initial (and very naive) generator and go from there.

- [x] add rely and guar nodes to AST
- [x] add Parser and TC support for new nodes
- [ ] refactor pog to support for multiple generation rules
- [ ] implement initial, naive collection of R/G obligations

**Comment by peterwvj** [comment]
This won't be done
