### ISSUE TITLE
Unify VDM libs between overture and example packager

### ISSUE THREAD

**Issue by ldcouto** [overturetool/overture#348]
(This issue is a continuation of #343).

As discussed in #346, we need to have a single set of VDM libs. At the moment we have 2: 
* one in the documentation folder (the *true* libs).
* one in the resources of example-packager.

I believe this fix needs to be implemented in example packager. The current code already copies example sources from the documentation folder so it cannot be too hard to do the same for the libs.

@joey-coleman , who is best suited to do this? My knowledge of example packager is very limited.

**Comment by joey-coleman** [comment]
Closed; created a bug for this at overturetool/example-packager#1
