### ISSUE TITLE
Warning in VDM libraries

### ISSUE THREAD

**Issue by peterwvj** [overturetool/overture#363]
In general there should be no warnings from the VDM libraries appearing in the Problems view in Overture. However, if you import the VDMUnit library you get the following warning: 

``` 
Recursive function has no measure. VDMUnit.vdmpp line: 533
``` 

The measure function is missing for the following function:
~~~
public static ToStringInt : int | nat1 | nat -> seq of char
ToStringInt(val) ==
  let result : int = val mod 10,
      rest : int = val div 10
  in if rest > 0 then
       ToStringInt(rest) ^ GetStringFromNum(result)
     else GetStringFromNum(result)
pre val >= 0;
~~~

**Comment by joey-coleman** [comment]
I'm referencing overturetool/example-packager#1 on this, as fixing that should also check which lib version had the error.
