### ISSUE TITLE
Automation of UI tests for releases

### ISSUE THREAD

**Issue by nickbattle** [overturetool/overture#383]
We need a way to quickly - preferably automatically - run a set of tests before product release to check that all of the basic operations of the tool are sound.
The following is a suggested list of UI aspects that we ought to test
```
    ​1. Project Creation​
        For each type: SL, PP, RT
            File/New/Project
            Check inclusion of libraries
        Check creation of new files in a project
    2. Editor
        Check for syntax errors as you type
        Check for type checking as you save
        Check editor matches Outline view and Outline navigation works
        Check problems appear in Problems view and link with editor
    3. Execution
        Creation of a launcher
        Check entry point, remote control and Console modes
        Check generate coverage, including PDF output
        Check runtime switches
        Check output appears in Console
        Check the Quick Interpreter - including expression recall
    4. Debugging
        Check the layout of the perspective
        Create a breakpoint and check stack
        Check single stepping, step into, step over and stop
        Debug multi-threaded spec with breakpoints
        Check that invariant failures trap into debugger
        Check that deadlock traps into debugger
        Check variable displays at breakpoint, including history counters
        Try skip all breakpoints
        Create some "watches" and check they are evaluated at breaks
    5. Combinatorial Testing
        Check the layout of the perspective
        Perform a basic CT test and check results
        Perform a large CT test and check nesting of results
        Perform a CT test with filtering and check results
    6. Proof Obligations
        Check the layout of the perspective
        Generate a reasonable set of POs and check display
        Check linked navigation in Editor view
    7. Workspace Settings
        Check for classic/VDM10 mode switching
        Check VDMTools integration
    8. Code Generation
        Check basic generation works
    9. Miscellaneous
        Check basic Eclipse functions, like Find in Files, Search etc.
        Check project export and import works
        Check the Help/About screen is accurate
```

**Comment by peterwvj** [comment]
We can move this list to a wiki page and make it part of the release process. I would like to close this issue because I don't think anybody is working on it. @pglvdm can you say more about this.

**Comment by pglvdm** [comment]
Here we have a MSc thesis student user the supervision of Stefan. I don't care where it is placed but the target here is to come up with a new solution for being able to do auto testing of UI stuff and use Overture as a case study

**Comment by ldcouto** [comment]
So, this student is working on this list?

**Comment by pglvdm** [comment]
Milos Chabada <chabada.milos@gmail.com>

**Comment by peterwvj** [comment]
I suggest that we move this list to some wiki page and maintain it there. @ldcouto where do you think we should put it? Maybe the release page? If we do that then we can close this issue

**Comment by ldcouto** [comment]
I think a wiki page is good. But it should be a standalone page (UI
Checklist or some such).

The release process links to that page as part of the RC testing.

**Comment by peterwvj** [comment]
Okay - that's done. The checklist is a available at https://github.com/overturetool/overture/wiki/UI-Testing-Checklist . Also, the RC testing section has a link for the UI testing checklist page.

Maintenance of the UI Testing checklist should be done on the wiki page.

I'm closing this issue.
