### ISSUE TITLE
self not in scope in invariant definitions

### ISSUE THREAD

**Issue by joaopascoalfariafeup** [overturetool/overture#390]
Hi,
I get the error 'self not in scope' in invariants' expressions as in the example below.
I think VDMTools support such expressions.
Can you confirm?

Thank you,
João Pascoal Faria
University of Porto, Portugal

class Person
  instance variables 
     private children: set of Person := {};
     private father: [Person] := nil;
     private mother: [Person] := nil;  
     inv father <> nil => self in set father.children;
     inv mother <> nil => self in set mother.children;
     inv forall c in set children & self = c.mother or self = c.father;
end Person

**Comment by msandim** [comment]
I also found an interesting workaround:

Just add an instance variable (e.g. ```private true_self: Person;```) and in the Person's constructor, add the line ```true_self := self```. This way you can use ```true_self``` (instead of ```self```) in the invariant! :smiley:
