### ISSUE TITLE
Remove Interpreter Tests based on old framework

### ISSUE THREAD

**Issue by ldcouto** [overturetool/overture#395]
A while back I converted the interpreter tests to the new test framework. But we still have the tests based on the old framework running. So, every test runs twice now.

This was not a big deal until now but I was adding a new test for #394 and there were a few issues with handling result files from two different frameworks. 

I'd like to delete all the tests that use old framework. I'll do this soon, if there are no objections.

**Comment by peterwvj** [comment]
This is part of improving the test framework See #483 

I'm closing this one..
