### ISSUE TITLE
Unresolved type parameters in pre-conditions

### ISSUE THREAD

**Issue by peterwvj** [overturetool/overture#402]
There are problems with resolving type parameters of a pre conditions. The problem can be shown by type checking the spec below and afterwards inspecting the type parameters of the pre-condition `pre_op`.

This is a problem with the type checker and as a consequence it may lead to a crash in the Java code generator as described in issue #400.

~~~
class A

 operations

public op:(A)==> ()
op(-) == 
 skip
 pre true; 

end A
~~~
The produced pre condition takes the following form:

~~~
private pre_op: ((unresolved A`A) * A +> bool)
    pre_op(-, self) ==
true
~~~

**Comment by nickbattle** [comment]
This sounds like the other issue we had? VDMJ "shares" the parameters with
the pre/post_op functions, so when the parameters are checked, the
pre/post_op parameters are checked too. But ASTv2 has separate AST nodes
for the pre/post_op parameters, so they need to be checked explicitly.​

​Can we not apply a similar fix?​

**Comment by peterwvj** [comment]
What issue are you thinking of in particular? To me it sounds like issue #400, which is solved as a consequene of this fix. Now thinking about it I forgot to look at post conditions, but this should be reported as a separate bug.

**Comment by nickbattle** [comment]
​Yes, #400. Is this a new bug or not?​

**Comment by peterwvj** [comment]
Sorry for the confusion. It's the same problem as #400, but I decided to create a new issue since issue #400 is presenting it as a problem with the code generator (which it is not). The problem is with the type checker really. For the sake of documentation I think it is better to have a more accurate issue for the problem. If you disagree let me know. This issue and issue #400 is linked via references.
