### ISSUE TITLE
Problem with access specifiers in traces

### ISSUE THREAD

**Issue by peterwvj** [overturetool/overture#405]
The spec below shows how it is possible to access a private member of another class in a trace. Although `a` is a private field of class B there is nothing preventing class C from accessing it via `b.a`, as shown in the trace `T`. I would expect a type error here.

If you, however, try to access the other private member of class B `b.x` (for example by changing the trace to `T: b.a.op(b.x);` you get the error `Error 3092: Inaccessible member x of class B in 'C' (A.vdmpp)` (which I think is meaningful).

Overture and VDMJ works the same in both cases.

~~~
class A

operations

public op : nat ==> nat
op (x) == return x;

end A

class B

instance variables

private a : A := new A();
private x : nat := 1;

end B

class C

instance variables

b : B := new B();

traces

T: b.a.op(2);

end C
~~~

**Comment by nickbattle** [comment]
Interesting bug. It's the same in VDMJ, and it only fails with operation calls (rather than, say, expressions). The following fails in the body of class C, whereas it works with "return b.a.op(2)".
```
operations
    op: () ==> nat
    op() == b.a.op(2);
```
I'll look at it.

**Comment by nickbattle** [comment]
Curiously, the type checking of the object field designator was not making an access check. Now fixed in ncb/development.

**Comment by peterwvj** [comment]
Good catch - thanks Nick
