### ISSUE TITLE
Problem running the SmokkingPP examples

### ISSUE THREAD

**Issue by gkanos** [overturetool/overture#413]
I imported the project normally from "import ->Overture examples" and  I tried to run the model with these 2 way:
1) I setup the entry point as World.Run() and I got the following error:
`internal error`
`Main 206: Error evaluating code`
`Detailed Message: internal error`
2) I tried with the remote control setup in the the run configuration and I got the following error:
`Exception in thread "main" java.lang.NoClassDefFoundError: org/overturetool/vdmj/debug/RemoteControl`

**Comment by nickbattle** [comment]
​Was this with the official Overture 2.1.6?​

**Comment by gkanos** [comment]
Yes for the Linux version that I downloaded.

**Comment by peterwvj** [comment]
Based on the error message you can tell that it tries to look up a class in a package that conforms to the Overture version 1 package structure. So probably what needs to be done is simply taking the Java code that the model relies uses (the GUI implementation), and then fixing the imports.

I remember doing this for a lot of other GUI based models at one point, but it seems like this one was being missed.

**Comment by gkanos** [comment]
I did change all the import from the Java file to the new structure, see example below:
`org.overture.interpreter.debug.RemoteControl;` 
but when I run it from the remote control it still gives me the same error.
`Exception in thread "main" java.lang.NoClassDefFoundError: org/overturetool/vdmj/debug/RemoteControl`
Does it requires another configuration as a project?

**Comment by peterwvj** [comment]
The examples have been moved and are now located in a separate repository. What you will have to do is to first: fix the model, and then generate the zip with all the examples.

Then from Overture you will have to run a command that downloads the examples to Overture. So assuming you have fixed the model (and the Java code) you will have to run the following commands:

Run `mvn clean` in <overture>/externals
then `mvn -Pforce-download-externals`

Does this help?

**Comment by ldcouto** [comment]
FYI, examples are in https://github.com/overturetool/documentation

**Comment by gkanos** [comment]
Closed with 461afb8d1eca9a8204e77f6ab7f2dd88dfc92ab0

**Comment by peterwvj** [comment]
Cool you fixed it. What branch is it on?

**Comment by gkanos** [comment]
overture/documentation
