### ISSUE TITLE
Problems running Overture with JDK/JRE 8 on Windows

### ISSUE THREAD

**Issue by joey-coleman** [overturetool/overture#414]
Overture fails to launch on Windows with JDK 8 installed.  The following error message was produced on Gareth's machine; he got around it by removing Java  8 and installing Java 7.

```
Error: Registry key 'Software\JavaSoft\Java Runtime Environment'\CurrentVersion' has value '1.8', but '1.7' is required.
Error: could not find java.dll
Error: Could not find Java SE Runtime Environment.
```

**Comment by ldcouto** [comment]
32-bits windows, fresh Java 8 install works.

**Comment by ldcouto** [comment]
Also works for 32-bit windows with Java 7 upgraded to 8.

**Comment by ldcouto** [comment]
Also works for 64 bit windows with concurrent 32 bit Java 8 and 64 bit java 7

**Comment by ldcouto** [comment]
All of the above also hold for version 2.0.6 (the version the problem was originally reported on),

**Comment by gkanos** [comment]
@ldcouto 
Can it be that only the 64bit version of Java 8 is causing problem? Or a specific release of Java 8?
Because from your last comments these looks the only logical possibilities.

**Comment by ldcouto** [comment]
Also works on 64 bit windows 7 with concurrent 64 bit java 7 and Java 8.

Both 2.2.0 and 2.0.6.

**Comment by ldcouto** [comment]
Everything also works on standalone 64bit Winows 64 bitJava 8

**Comment by ldcouto** [comment]
Also works using the JDK instead of the JRE

**Comment by ldcouto** [comment]
So... 

Since all these permutations work, think there is no actual problem here.

Googling around found many instances of this problem. Blame seems to go to Oracle and the bizarre way in which multiple Java versions are set up. The official fix seems to be uninstalling all Java versions and then simply installing Java 8. Suggest adopting same policy if this comes up again.

In the meantime, think bug can be closed.

**Comment by joey-coleman** [comment]
Agreed, we'll file this under 'not-our-problem' :).  Thanks for testing out all of the variations.

**Comment by lausdahl** [comment]
This issue both happen for Overture and Crescendo. It is only overture which displays:
~~~
Error: Registry key 'Software\JavaSoft\Java Runtime Environment'\CurrentVersion'
has value '1.8', but '1.7' is required.
Error: could not find java.dll
Error: Could not find Java SE Runtime Environment.
~~~

The solution is to delete these files from `c:\Windows\System32`

- java.exe
- javaw.exe

We have to make a note or FAQ somewhere to assist the user in solving this. It is correct that this is a Java 8 installer problem which sucks in almost all possible ways. It doesn't install the stuff it should be removed more than it is asked for - not a great installer.

**Comment by ldcouto** [comment]
Since the FAQ is a website thing, I've created an issue there: https://github.com/overturetool/overturetool.github.io/issues/16

Closing this one again.
