### ISSUE TITLE
Tic-tac-toe CT errors in 2.2.0

### ISSUE THREAD

**Issue by nickbattle** [overturetool/overture#415]
The tic-tac-toe model in the VDMSL examples produces a "null" (pointer exception) error for every test case in Overture 2.2.0. Other CT tests seem OK. The error occurs if you run the full suite or just send one test to the interpreter. It similarly fails from the Console:
```
> runtrace ALL 1
Generated 15120 tests
Test 1 = XO`play([<CROSS>, <NOUGHT>], [mk_Pos(1, 1), mk_Pos(1, 2), mk_Pos(1, 3), mk_Pos(2, 1), mk_Pos(2, 2)])
Result = [null, FAILED]
Executed in 2.592 secs. 
Some tests failed or indeterminate
>
 ```

**Comment by nickbattle** [comment]
In the debugger, there is missing type information for the mk_Pos(1,1) value in the argument passed. It's as though a type check hasn't been executed on the expanded tests.

**Comment by nickbattle** [comment]
I can't see where type checking occurs during trace expansion. It fails in tic-tac-toe because the mk_Pos type has an invariant, which needs to use the type at runtime. In VDMJ, the tests are type checked during expansion (in the equivalent of ANamedTraceDefinitionAssistantInterpreter getTests).

**Comment by nickbattle** [comment]
It works in 2.1.2, but not in 2.1.4 or 2.1.6.

**Comment by peterwvj** [comment]
I looked into the log of the ANamedTraceDefinitionAssistantInterpreter and I can see that the type check you are talking about was removed from this assistant in commit b6a7e. From what I can tell the idea was to postpone checking to a later time but this approach seems to be flawed.

**Comment by nickbattle** [comment]
​Who made that commit?​

**Comment by peterwvj** [comment]
Kenneth is the author but it could be part of some joint work that Kenneth and I did on traces. I don't really remember the commit to be honest. I will talk to him about it.

**Comment by nickbattle** [comment]
I'm marking this as an urgent bug. Lots of the non-trivial CT tests that I have are failing, and I can't demonstrate the CT feature of Overture to anyone.

**Comment by peterwvj** [comment]
Yes I see. Do you have a small model that demonstrates the problem?

**Comment by nickbattle** [comment]
Tic-tac-toe isn't that big, but I'll try to create a smaller one. I think it
just needs to use values that have an invariant.

**Comment by nickbattle** [comment]
OK, here's the simplest I could make fail:
```
class A
types
	R :: a: nat
	inv r == r.a < 10;
	
operations
	op: R ==> ()
	op(-) == skip;
	
traces
	T1: op(mk_R(1));

end A
```

**Comment by lausdahl** [comment]
@peterwvj please generate the test results and confirm that it fixes the issue(see commit above)

**Comment by peterwvj** [comment]
Thanks for your work, Kenneth! The simple version of the XO model (the first 9 tests) break the invariants (VDMJ produces the same) so that's good. Also the sample model Nick posted produces what you should expect.
