### ISSUE TITLE
fixme: only used in 1 class. Move it over.

### ISSUE THREAD

**Issue by lausdahl** [overturetool/overture#419]
There are a lot of fixmes in the code like: `only used in 1 class. Move it over.` these should be removed. Maybe it is fixed but just a left over from the migration.

Can @gkanos  take a look to see how to fix this.

see https://overture.au.dk/jenkins/view/Overture/job/overture-test/180/tasksResult/HIGH/

**Comment by gkanos** [comment]
If I got it correct, I will need to remove the FIXME tag wherever there is no need for it?

**Comment by peterwvj** [comment]
The idea is to clear trivial FIXMEs and remove those that do not need to be there anymore. Many of these FIXMEs can probably be deleted and right now it is difficult to tell if some of the FIXMEs truly require work or not

**Comment by ldcouto** [comment]
The  `only used in 1 class. Move it over` fixmes are related to the assistant clean up done in #330.

They all identify assistants or assistant methods that are only used in 1 place and as such are candidates for removal or deletion. If you want to address that, I'm all for it but do not just delete the fixmes.

**Comment by peterwvj** [comment]
What's the progress on this issue @gkanos?

**Comment by gkanos** [comment]
I have fix more of these cases but I am not sure if that was all. In the branch gk/main I have push what I have done on this

**Comment by gkanos** [comment]
Now in my branch gk/main, I have completed the removal of all the used only 1 methods though a series of commits. Merge it to development to close this issue. @peterwvj , @afterkelsen

**Comment by peterwvj** [comment]
Cool, George - thanks. I'll try to merge it into pvj/main.

**Comment by peterwvj** [comment]
I merged your stuff into pvj/main. Everything seems to be fine (all tests pass).
