### ISSUE TITLE
POG not implemented for while loops

### ISSUE THREAD

**Issue by pglvdm** [overturetool/overture#420]
~~~
class TestPOG

operations

public Test: () ==> ()
Test() ==
  while true do
    skip;

end TestPOG
~~~

**Comment by ldcouto** [comment]
I'm not sure what obligation should be generated here. VDMJ prints `...` and VDMTools prints nothing.  

To prove loop termination, we need loop variants and stuff, which are currently not in VDM.

**Comment by nickbattle** [comment]
​Yes, the VDMJ position here is "We don't know how to generate POs for
this, but here's a reminder that you have an obligation of some sort
anyway" :-)​

**Comment by ldcouto** [comment]
Currently Overture prints a `NotYetImplemented` string. Perhaps the ellipsis would be a better approach?
