### ISSUE TITLE
New function for current system time

### ISSUE THREAD

**Issue by ldcouto** [overturetool/overture#426]
We've been working on a model where we would like to so really basic performance tests.

To do this, I think it would help to have a function that gives the current system time like`System.currentTimeMillis` in Java. I think this is something that should be pretty easy to VDMUnit, yeah?

@nickbattle , I'd be up for doing it. It's basically just editing the VDMUnit source and the counterpart Java files? Or is there some official process for adding something to the libs

**Comment by nickbattle** [comment]
​I don't see what this has to do with VDMUnit? It sounds more like
something generally useful to put in the VDMUtils library to me?​

But wherever it goes, yes, all you have to do is to declare it in (say)
VDMUtil.vdm and VDMUtil.vpp with a body of "is not yet specified". Strictly
it is an operation as it returns a different value each time. Then you add
a method to VDMUtil.java with the same name and (presumably) no parameters
that returns a Value. The body would be "return new
natValue(System.currentTimeMillis());".

​If you want to make it official, you should submit an RM to the Language
Board as they own the standard libraries.​

**Comment by ldcouto** [comment]
Yeah, I meant VDMUtil. Duh :(

I'm happy to submit a request but only if this is something  that would be useful.

**Comment by nickbattle** [comment]
Well, it's something that you need, so it is useful in at least one case :)

It might at least be useful to remind the LB that we do look after the
libraries (and get some processes in place to do that).

**Comment by ldcouto** [comment]
Well, I like fighting against feature creep so one case is not enough in my mind :)

But I'll write it up, no problem. Even though my last submission to the LB caused a lot of trouble

**Comment by ldcouto** [comment]
Done in https://github.com/overturetool/language/issues/31.

Use this issue to report back on the progress of the RM so it eventually goes in the release notes (or not).

**Comment by ldcouto** [comment]
RM rejected. Closing this.
