### ISSUE TITLE
JVM version misreported?

### ISSUE THREAD

**Issue by SteveR-Ncl** [overturetool/overture#429]
A student in my class is having trouble setting up Overture on his Mac, due to a warning about his version of JVM. He says he's got 1.8 installed, but he's getting the error "Version 1.6_65 of the JVM is not suitable for this product. Version 1.7 or greater is required"

Have you seen any problems with incorrect version being reported? If that's unlikely, I'll get him to check he hasn't actually got 2 versions of JVM on his machine.

cheers, Steve

**Comment by ldcouto** [comment]
Hey Steve.

There are 2 possibilites. The first is, like you say, he has multiple JVMs installed (the installer for Java 8 is famous for causing a lot of path issues with multiple JVMs).

There is also a possibility that he has the 64 bit version of Overture and 32bit Java or vice-versa. 

I can help trace the problem but I'll need more information. What's the output of `java --version` on the command line? And the output of `echo `$JAVA_HOME`?

**Comment by ldcouto** [comment]
This sounds like a similar problem: http://stackoverflow.com/questions/24598465/eclipse-in-os-x-uses-different-version-of-java-than-cli

**Comment by SteveR-Ncl** [comment]
Thanks Luis - I've passed that on to the student, will let you know what
he comes back with.
-Steve

**Comment by peterwvj** [comment]
Related to #414

**Comment by ldcouto** [comment]
@peterwvj , I'm not 100% sure it is actually. It might be, though.

**Comment by ldcouto** [comment]
Hey @SteveR-Ncl , just checking in to make sure this is solved on your end.

**Comment by SteveR-Ncl** [comment]
Hi Louis, yep, sorry for not getting back, the student hasn't responded to me (I sent him your suggested fixes) so I assume it's resolved. I'll close.
