### ISSUE TITLE
Overture closes with error when expanding and collapsing traces on a Mac OSX

### ISSUE THREAD

**Issue by miranha** [overturetool/overture#430]
Running combinatorial testing with the following model:

class SimpleTrace

traces
tr_id :
let a in set {1,2} in IO`print(a)

end SimpleTrace

Expanding and then collapsing the trace, see picture below, gives an error and Overture closes.

![image](https://cloud.githubusercontent.com/assets/8570378/6598616/27ce727a-c805-11e4-8570-3198aefc1c55.png)

![image](https://cloud.githubusercontent.com/assets/8570378/6598995/6e1c42c8-c807-11e4-8479-a1f60c3265b3.png)

I works on Windows and Linux, so it seems to be a Eclipse/UI/MAC related issue.

Session data is:
eclipse.buildId=unknown
java.version=1.7.0_45
java.vendor=Oracle Corporation
BootLoader constants: OS=macosx, ARCH=x86_64, WS=cocoa, NL=en_US
Framework arguments:  -keyring /Users/Miran/.eclipse_keyring -showlocation
Command-line arguments:  -os macosx -ws cocoa -arch x86_64 -keyring /Users/Miran/.eclipse_keyring -showlocation

**Comment by peterwvj** [comment]
When we upgrade to Luna we should check if this goes away #450

**Comment by lausdahl** [comment]
This seems to be this bug https://bugs.eclipse.org/bugs/show_bug.cgi?id=422371

```
Thread 0 Crashed:: Dispatch queue: com.apple.main-thread
0   libsystem_kernel.dylib        	0x00007fff996e3286 __pthread_kill + 10
1   libsystem_c.dylib             	0x00007fff91cd7b53 abort + 129
2   libjvm.dylib                  	0x0000000105a9410f os::abort(bool) + 25
3   libjvm.dylib                  	0x0000000105ba0018 VMError::report_and_die() + 2308
4   libjvm.dylib                  	0x0000000105a95ac9 JVM_handle_bsd_signal + 1083
5   libsystem_platform.dylib      	0x00007fff8b98df1a _sigtramp + 26
6   libobjc.A.dylib               	0x00007fff94543a98 getIvar(objc_class*, char const*) + 28
7   libobjc.A.dylib               	0x00007fff94535f54 _class_getVariable + 140
8   libobjc.A.dylib               	0x00007fff9453c80c object_getInstanceVariable + 47
9   libswt-pi-cocoa-4335.jnilib   	0x00000001131da9f3 Java_org_eclipse_swt_internal_cocoa_OS_object_1getInstanceVariable + 281
10  ???                           	0x000000010636ac5f 0 + 4399213663
11  ???                           	0x0000000106369068 0 + 4399206504
12  ???                           	0x0000000106128233 0 + 4396843571
13  ???                           	0x0000000106128058 0 + 4396843096
14  ???                           	0x00000001061224e7 0 + 4396819687
15  libjvm.dylib                  	0x000000010594eb58 JavaCalls::call_helper(JavaValue*, methodHandle*, JavaCallArguments*, 
```

Upgrade Eclipse to version 4.4.2 at least build M20150128-1000 where it has been verified fixed
