### ISSUE TITLE
Command line coverage only works with absolute filenames

### ISSUE THREAD

**Issue by nickbattle** [overturetool/overture#437]
If you run the Overture-2.2.3-SNAPSHOT.jar and use the "coverage" command, you will not see any lines marked as executable, nor see any line coverage recorded, unless you pass an absolute filename for the source, like "/home/nick/test.vdm". If you only pass "test.vdm" (because you're in /home/nick) the coverage will not work.

The problem seems to be the use of CloneableFile in some places and not others. This class converts Files to absolute values in the constructor (which is controversial). In particular, the list of source files from the interpreter seems to be a list of CloneableFiles, but the files in LexLocations are not. This difference causes the coverage to think that the locations are not within the spec's files.

It may be that Overture (internally) always deals with absolute file paths, so this only shows up in the command line tool.

Can someone take a look?

**Comment by ldcouto** [comment]
I can try to look at it but will not have time before easter.

Either way, this is will not go in 2.2.4 release :(

**Comment by nickbattle** [comment]
​That's fine. It's hardly critical as the command line is rarely used,
command line coverage even less so, and there is a workaround (using full
pathnames).​ An obvious "hack" would be to use CloneableFiles in more
places, such as LexLocations. But I know the Overture coverage stuff is
quite complicated and naively making this change could have side effects
that I can't guess.

I was a bit surprised that the CloneableFile constructor "widens" the File
to an absolute path as it does. Why not make its behaviour the same as
File, and then fix whatever needs absolute file paths separately?

**Comment by lausdahl** [comment]
I updated to clonable file for testing and now I get this result:

~~~
> coverage
Test coverage for test.vdmpp:

  class A
  
  operations
  public static op : ()==>()
+ op()==skip
  
  
  
  end A

Coverage = 100.0%
~~~

is that what is expected as coverage from `p new A().op()`

**Comment by nickbattle** [comment]
Hi Kenneth,

Yes, it only highlights lines that have executable content.

Cheers
nick

-----Original Message-----
