### ISSUE TITLE
Disable Trivial PO Status

### ISSUE THREAD

**Issue by ldcouto** [overturetool/overture#441]
In the old string POG, trivial POs were marked in the IDE (grey check). This doesn't happen for the AST POs so the status column is not very helpful at the moment. It should be disabled until we have an actual use for it.

**Comment by nickbattle** [comment]
We need to make some changes to the IDE documentation to remove the description of this feature, unless we plan to re-introduce it quickly.

Would it not be possible to run the old "trivial" pattern checking against the toStrings of the new AST POs?

**Comment by ldcouto** [comment]
I don't see any reason it wouldn't be possible. The reason for disabling it was that since there is a (long-gestating) plan to incorporate theorem proving, the idea was to let the prover take care of all proofs.

But I agree the manual needs to be updated, since the feature is removed. But the issue should go in the docs repo: https://github.com/overturetool/documentation/issues

**Comment by nickbattle** [comment]
OK, I've created a documentation bug.

**Comment by nickbattle** [comment]
Closing this one again :-)
