### ISSUE TITLE
"Could not create the view..." 

### ISSUE THREAD

**Issue by MarkoSchuetz** [overturetool/overture#442]
I launched Overture 2.2.4 and had errors 
Could not create the view: org.overture.ide.plugins.poviewer.views.PoOverviewTableView
Could not create the view: org.overture.ide.plugins.poviewer.views.PoTableView

I then tried version 2.1.6, but had the same results. Unfortunately, I cannot attach the log.

**Comment by nickbattle** [comment]
Could you tell us what platform you are using firstly. And it would also be useful to know something about the model you were trying to generate POs for as well - dialect and so on.

**Comment by MarkoSchuetz** [comment]
java.version=1.7.0_79
java.vendor=Oracle Corporation
BootLoader constants: OS=linux, ARCH=x86_64, WS=gtk, NL=en_US
Command-line arguments:  -os linux -ws gtk -arch x86_64

I was using the alarms model is from the tutorial examples. I'm afraid I can not be more specific about the model since this was a model still in my workspace from the first time I tried familiarizing with Overture some time ago.

**Comment by peterwvj** [comment]
Hi Marko.

I have seen strange errors before where plugins do not load properly if you try to load a corrupted workspace. Could that be the case? Is the workspace you are trying to load a (previous) Crescendo workspace?

So just to make sure... Can you try to switch to workspace to a location that has not previously been used as a workspace. Go to "File" -> "Switch Workspace" -> "Other" and then point Overture to newly created folder.

Does the problem still occur?

**Comment by MarkoSchuetz** [comment]
Thanks peterwvj,

loading the examples in a fresh workspace solved my problem.

**Comment by ldcouto** [comment]
Great to hear Marko.

Closing this.
