### ISSUE TITLE
Launcher remembers entry point, even when using Console

### ISSUE THREAD

**Issue by nickbattle** [overturetool/overture#447]
If you create a launcher, and run (say) TEST'run(), that is fine. And if you then change the launcher to use the Console mode, that is also fine (and the entry point boxes are greyed out, though still show TEST'run()). But if you subsequently change the specification to remove the TEST module, even though the launcher is in Console mode, you will get an error at initialization:
```
Initialization: java.lang.Exception: Module TEST not loaded
```
So I think when you switch to Console mode, the entry point boxes should be cleared.

**Comment by ldcouto** [comment]
Done in db111ece
