### ISSUE TITLE
Update of Eclipse version: The kepler Eclipse version is not longer properly mirrored

### ISSUE THREAD

**Issue by lausdahl** [overturetool/overture#450]
We have discovered that the eclipse kepler download site we point to in the build no longer is properly mirrored by Eclipse.org in fact it is only possible to find 4.3 SR2 repositories but these only includes Eclipse and none of the dependent plugins Overture also needs.

Effect: If the local p2 repo in a local build is deleted then there is no easy way to get it back.

Solutions: 

1. Figure out what we need from the kepler release and host it statically. We cannot use artifactory since Eclipse proxy is not supported. Using the standard mirroring is also not possible since it requires c. 2 TB
2. Switch to a current version of Eclipse this will remove the issue

**Comment by ldcouto** [comment]
Please fix the id of the repository too :)

BTW, strictly speaking we are still on Eclipse 3.8 in terms of application framework.

**Comment by peterwvj** [comment]
After Kenneth upgraded to Luna I checked out `kel/main`, built a standalone and did some quick testing of the IDE. It performed well on a Linux 64 bit machine and I did not experience any problems. Things I tried:

* Executing models for all three dialects
* Generated POs
* Basic use of the editor
* Code Generation
* Combinatorial testing, including inspection of test results
* RT log viewer
* Basic use of the editor
