### ISSUE TITLE
Make new code generation functionality accessible via the Overture IDE

### ISSUE THREAD

**Issue by peterwvj** [overturetool/overture#451]
Below are some code generation features that hopefully will make it into the next release of Overture.

* [x] Add support for SL to Java code generation via the IDE
With the exception of renamed definitions, the SL to Java code generator supports most of the definitions, expressions and statements that the VDM++ to Java code generator does. Consider also adding support for renamed definitions if time allows.

* [x] Add an option to disable formatting of code (it's pretty slow).
Feature requested by KEL. Also make it an option/argument for the command-line version of the Java code generator.

* [x] Make it possible to invoke the JML generation feature via the IDE
* [x] Add configuration support for the JML generation feature so the user can enable/disable it
* [x] Update the maven code generation plugin to support disabling of code formatting and selection of VDM dialect
* [x] Supress warnings in the generated code. Requested by Kenneth
* [x] Make sure Luis' fix for template loading gets merged in
* [x] Port over old Java code generator tests to the new test execution system
Most of the work here is done. Some tests are left are be ported over to the new setup.
* [x] Improve error reporting when template do not parse
* [x] Upgrade maven tests to support compilation, execution and validation of the generated code
* [x] Improve new Java code generation test execution system by re-generating Java code directly instead of parsing it from .result files.
* [x] Cleanup new Java code generation test execution system
Note: also make sure that the Java settings and IR settings are set up correctly prior to producing the code
* [x] Update old Java code generator tests over to the new test framework
* [x] Re-enable unsupported modelling test case that has temporarily been taken out

**Comment by ldcouto** [comment]
FYI, the commit for the template fix is 498c80394

**Comment by peterwvj** [comment]
Thanks Luis. I cherry-picked it into my branch.

**Comment by ldcouto** [comment]
Better reporting of template errors: db55c54f2035f
