### ISSUE TITLE
Can't launch GUI examples in OpenJDK

### ISSUE THREAD

**Issue by peterwvj** [overturetool/overture#452]
There has been a change that breaks the GUI based VDM model examples. Right now I can't make it work with any of the models on Linux. Below is the output you get when you try to run the launch configuration that ships with VeMoRT, which used to work. We really need to find a way to test this automatically.

~~~
**
** Overture Console
**
0: Environment created: Some aren't used to an environment where excellence is expected
Initialization: Internal 0059: Failed in native method: null
Internal 0059: Failed in native method: null
	at org.overture.interpreter.util.Delegate.invokeDelegate(Delegate.java:256)
	at org.overture.interpreter.runtime.state.SClassDefinitionRuntime.invokeDelegate(SClassDefinitionRuntime.java:54)
	at org.overture.interpreter.assistant.definition.SClassDefinitionAssistantInterpreter.invokeDelegate(SClassDefinitionAssistantInterpreter.java:603)
	at org.overture.interpreter.values.ObjectValue.invokeDelegate(ObjectValue.java:534)
	at org.overture.interpreter.eval.DelegateExpressionEvaluator.evalDelegatedANotYetSpecified(DelegateExpressionEvaluator.java:120)
	at org.overture.interpreter.eval.DelegateStatementEvaluator.caseANotYetSpecifiedStm(DelegateStatementEvaluator.java:18)
	at org.overture.interpreter.eval.DelegateStatementEvaluator.caseANotYetSpecifiedStm(DelegateStatementEvaluator.java:9)
	at org.overture.ast.statements.ANotYetSpecifiedStm.apply(ANotYetSpecifiedStm.java:304)
	at org.overture.interpreter.values.OperationValue.localEval(OperationValue.java:420)
	at org.overture.interpreter.values.OperationValue.eval(OperationValue.java:270)
	at org.overture.interpreter.eval.StatementEvaluator.caseACallObjectStm(StatementEvaluator.java:293)
~~~

**Comment by nickbattle** [comment]
So the "Internal 0059: Failed in native method: null" is telling us that the invoked code (the Java "operation", as far as Overture is concerned) is throwing a null pointer exception. Unfortunately, the trace doesn't tell us why, but if this is reproducible in a debug environment, we should be able to track down the NPE.

**Comment by peterwvj** [comment]
Luis and I looked a bit more into it apparently it only seems to be a problem with OpenJDK so if you are using the Oracle JDK, which I assume most people do anyway, the problem does not show. If I try to run the model without the IDE, and making the `graphics.jar` available on the classpath then the model executes fine. It also work if I do remote debugging of the model.

So maybe there is a difference in they way the Oracle JDK and OpenJDK uses the classpath.

**Comment by peterwvj** [comment]
@gkanos are you using OpenJDK? If so, do you mind confirming the problem on your machine?

**Comment by gkanos** [comment]
For me with openJDK v. 1.7.0.79 seems to work the VeMoRT example.

**Comment by peterwvj** [comment]
Okay thanks for checking. Did you try with the release candidate?

**Comment by gkanos** [comment]
@peterwvj  nope, I used the version 2.2.4

**Comment by peterwvj** [comment]
Okay. Do you mind trying with the release candidate also? Thanks.

**Comment by peterwvj** [comment]
Only my machine produces the problem although we have same Java setup. The only real difference between the machines we have is that mine is running a slightly different version of Ubuntu. Other than that the Java versions are exactly the same. Hopefully the problem is my machine...

~~~
OpenJDK Runtime Environment (IcedTea 2.5.5) (7u79-2.5.5-0ubuntu0.14.10.2)
OpenJDK 64-Bit Server VM (build 24.79-b02, mixed mode)
~~~~

**Comment by ldcouto** [comment]
I think you two should do a little pair-debugging so we can trace this issue. 

@peterwvj , I assume you have cleared workspaces, etc?

**Comment by peterwvj** [comment]
Yes the workspace is completely wiped.

**Comment by ldcouto** [comment]
Yeah, I figure as much. @gkanos , do you have 2 JDKs as well?

**Comment by gkanos** [comment]
What you mean 2 JDK's? I have this result when I give java -version :
~~~
java version "1.7.0_79"
OpenJDK Runtime Environment (IcedTea 2.5.5) (7u79-2.5.5-0ubuntu0.14.04.2)
OpenJDK 64-Bit Server VM (build 24.79-b02, mixed mode)
~~~~

**Comment by ldcouto** [comment]
Do you, like @peterwvj , also have the Oracle JDK installed?

**Comment by gkanos** [comment]
No, I don't

**Comment by gkanos** [comment]
Update: I run the VeMoRT example on Opensuse 13.2 with openJDK version 1.8.0.45 and still worked fine.

~~~
openjdk version "1.8.0_45"
OpenJDK Runtime Environment (build 1.8.0_45-b14)
OpenJDK 64-Bit Server VM (build 25.45-b02, mixed mode)
~~~

**Comment by peterwvj** [comment]
We're not able to produce the problem using very similar configurations. I'll close the issue for now. The problem is with my machine.
