### ISSUE TITLE
Wrong template construction for implicit operations and functions

### ISSUE THREAD

**Issue by miranha** [overturetool/overture#453]
The tool currently auto-completes the implicit operations and functions wrong:

![image](https://cloud.githubusercontent.com/assets/8570378/8227173/266944ee-15a5-11e5-9f78-a669617a2dfe.png)

![image](https://cloud.githubusercontent.com/assets/8570378/8227202/61fcf41a-15a5-11e5-8b5f-da223f2e3a36.png)

**Comment by ldcouto** [comment]
So, just for reference, there should be no arrow (`->` and `==>`) between the function parameters and the result name.
