### ISSUE TITLE
Overture tool on Debian crushes everytime

### ISSUE THREAD

**Issue by E-Hermo** [overturetool/overture#467]
<p>I have installed Debian 7 on my computer. I installed Overture tool (2.2.6) by downloading and extracting the .zip file. Every time I try to run Overture I get the following error message:</p>

<pre><code>

     # A fatal error has been detected by the Java Runtime Environment:
        #
        #  SIGSEGV (0xb) at pc=0x00007f7ea122673f, pid=11073, tid=140182465734400
        #
        # JRE version: Java(TM) SE Runtime Environment (8.0_60-b27) (build 1.8.0_60-b27)
        # Java VM: Java HotSpot(TM) 64-Bit Server VM (25.60-b23 mixed mode linux-amd64 compressed oops)
        # Problematic frame:
        # C  [libgdk-x11-2.0.so.0+0x5173f]  gdk_display_open+0x3f
        #
        # Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
        #
        # If you would like to submit a bug report, please visit:
        #   http://bugreport.java.com/bugreport/crash.jsp
        # The crash happened outside the Java Virtual Machine in native code.
        # See problematic frame for where to report the bug.
        #

</code></pre>

<p>Does anybody know how to fix this?</p>

<p>Thanks!</p>

**Comment by nickbattle** [comment]
It looks like this is 64-bit JRE 8 on Linux. I assume this is 2.2.6. Have we had problems with Java 8 before?

**Comment by E-Hermo** [comment]
No, I haven't noticed any problem before

**Comment by E-Hermo** [comment]
And yes, it's 2.2.6

**Comment by nlmave** [comment]
Check out https://bugs.eclipse.org/bugs/show_bug.cgi?id=430736

**Comment by E-Hermo** [comment]
Thanks! So it seems that updating glibc from 2.13 to 2.14 should fix this problem. I will try it!

**Comment by nickbattle** [comment]
Or possibly setting SWT_GTK3=0. Let us know how you get on.

**Comment by E-Hermo** [comment]
@nickbattle Yes! This works perfectly fine and lot easier that trying to update glibc in Debian Wheezy!! Executing:<code> $ export SWT_GTK3=0 && ./Overture </code> everything runs perfect. Thank you very much @nickbattle and @nlmave.

**Comment by nickbattle** [comment]
That's good news. Would you mind posting the solution (perhaps a link to this issue) on the StackOverflow query that you first raised?

**Comment by E-Hermo** [comment]
Done!
