### ISSUE TITLE
Error with launching the GUI part of the Conway Game of Life

### ISSUE THREAD

**Issue by pglvdm** [overturetool/overture#475]
When trying to launch
~~~
gui_Graphics`generations_animate(130,DIEHARD)
~~~
An error like:
~~~
Main 206: Error evaluating code
Detailed Message: Error 3182: Name 'gui_Graphics`generations_animate' is not in scope in 'Conway' (LaunchConfigurationExpression) at line 1:1
Initialization: java.net.SocketException: Connection reset
java.net.SocketException: Connection reset
	at java.net.SocketInputStream.read(SocketInputStream.java:189)
	at java.net.SocketInputStream.read(SocketInputStream.java:121)
	at java.net.SocketInputStream.read(SocketInputStream.java:203)
	at org.overture.interpreter.debug.DBGPReader.readLine(DBGPReader.java:622)
	at org.overture.interpreter.debug.DBGPReader.run(DBGPReader.java:843)
	at org.overture.interpreter.debug.DBGPReader.connect(DBGPReader.java:553)
	at org.overture.interpreter.debug.DBGPReader.startup(DBGPReader.java:561)
	at org.overture.interpreter.debug.DBGPReaderV2.main(DBGPReaderV2.java:533)
~~~
is reported.

**Comment by peterwvj** [comment]
It works on mine with the launch configuration below.

it setup like that on your machine? 
What operating system are you running?

![conway](https://cloud.githubusercontent.com/assets/5388919/10448899/47329a44-7190-11e5-9492-017db79e6696.png)
![conway](https://cloud.githubusercontent.com/assets/5388919/10448900/4917fa5c-7190-11e5-85c5-30593d684e25.png)

**Comment by pglvdm** [comment]
Great to see that it works at other platforms. I am trying this on mac running Mac OS.

**Comment by peterwvj** [comment]
Based on the error message you get it seems like you are trying to execute an operation called `gui_Graphics```generations_animate` in a module called `Conway` (see below). So it sounds like the launch configuration is not set up correctly.

That said, the error message is not very user friendly.

Peter, do you mind deleting your launch configuration and trying to set it up again?

 `Detailed Message: Error 3182: Name 'gui_Graphics`generations_animate' is not in scope in 'Conway' (LaunchConfigurationExpression) at line 1:1`

**Comment by pglvdm** [comment]
Indeed. Problem at my side. I close the issue.

**Comment by peterwvj** [comment]
Glad to hear it works!
