### ISSUE TITLE
Impure op called from pure undetected by TC

### ISSUE THREAD

**Issue by ldcouto** [overturetool/overture#482]
I could have sword we tested this. Anyway, the spec below yields no TC errors
```
class A
operations
public foo : () ==> int
foo () == return 0;
end A

class B
operations
public pure bar : () ==> int
bar () == new A().foo();
end B
```

By the way. VDMJ correctly reports the error:
```
Error 3339: Cannot call impure operation from a pure operation in 'B' (/home/ldc/dev/workspaces/ovt230-new/A/A.vdmpp) at line 12:15
```

**Comment by nickbattle** [comment]
It seems to be an omission. The test spec that I wrote to exercise all of the possible error codes calls impure operations from all sorts of pure places, like the argument to duration and cycles, pre/post ops and in the RHS of an assignment. But it never actually tries calling a simple operation directly :-)

It should be a simple fix.

**Comment by nickbattle** [comment]
Now fixed in ncb/development.
