### ISSUE TITLE
Private members can be redefined by a subclass

### ISSUE THREAD

**Issue by peterwvj** [overturetool/overture#484]
Overture, VDMJ and VDMTools all seem to allow `private` operations to be overloaded. For example, consider the spec below. Here `new A().Run()` evaluates to `2` and not `1` as I expected.

Unless there is a good reason for it then I don't think it should be allowed for a subclass to redefine the behaviour of a `private` member of a parent class. You can argue that this breaks encapsulation. For comparison, the equivalent Java program will returns `1` as Java does not allow `private` methods to be overridden.
~~~
class A

operations

private op : () ==> nat
op () == return 1;

-- Entry point
public Run : () ==> nat
Run () ==
let x : A = new B()
in
  x.op();

end A

class B is subclass of A

operations

private op : () ==> nat
op () == return 2;

end B
~~~

**Comment by tomooda** [comment]
The difference is from how instance attributes are resolved. It seems that Overture, VDMJ and VDMTools resolves any instance attribute at runtime (dynamically bound), whereas Java's private methods are resolved at compile-time (statically bound). 

At my best knowledge, the LRM only says that non-static private operations are instance attributes and private accessibility bans viewing the attribute from any class other than the defining class. So, I think Overture and other tools implement the language spec properly.

If we don't want private operations overridden by subclasses, we have two choices:
(1) to define "private attributes" as the third kind of attribute and specify that they are resolved at compile-time. (compatible to Java)
(2) to simply prohibit to override a private attribute and compilers check it in type checking. (more restrictive than Java)

In my opinion, (2) is simpler and  (1) will bring messy situation that "x.op()" given the same object "x" may point at different body of operation depending on where the "x.op()" expression is written.

**Comment by peterwvj** [comment]
Thanks for your input! I haven't found anything in the LRM that convinces me that this is a bug (I haven't marked it as one). I'm just not sure if the current design (allowing private members to be redefined) is well thought out. Whenever this sort of confusion shows up I think it's fine to use a restrictive solution (like your second proposal).

But thinking about it, if we choose to do this for both functions and operations then it also changes the way that OO invariants currently work. Right now invariant functions are `private` and not allowing `private` members to be redefined would mean that you can't change the invariant. I'm not sure we want this.

**Comment by nickbattle** [comment]
I think this sort of issue has come up before. I usually give two answers(!). The first is that the precise OO semantics of VDM++ are very poorly defined, and that is hopefully something we can start to address in 2016's LB. The second is that, when you look at the subtleties like this, you often find that OO languages differ. In this particular case, C++ functionality is similar to what VDMJ is providing - C++ makes a clear distinction between access specifiers (like "private") which define where something can be called from, and overriding, which defines what gets called. So it is perfectly legal to override a private member function in C++. In general, I find C++ semantics is better thought through than Java, but it is also a lot more complicated.

Your example is roughly like this in C++:
```
#include <stdio.h>

class A
{
private:
    virtual int op()
    {
        return 1;
    }

public:
    int test()
    {
        return op();
    }
};

class B : public A
{
private:
    virtual int op()
    {
        return 2;
    }
};

int main(int, char *[])
{
    A *x = new B();
    printf("Answer = %d\n", x->test());
}
```
The fact that the operation is private, means that it can only be called from within A. Other subclasses of A could not call it, for example. But that does not mean that what gets called is not overridden in a subclass (here, in B). So the main function produces:
```
Answer = 2
```
Unless something is clearly broken in VDMJ, I don't think we should tinker with the OO semantics until we know what we are trying to implement very clearly. As I said, I hope the semantics will get a lot clearer in 2016 :-)

**Comment by nickbattle** [comment]
There is a reasonable amount of discussion (and confusion!) about this on the web. One of the better links I found is this one:

https://en.wikibooks.org/wiki/More_C%2B%2B_Idioms/Non-Virtual_Interface

So I agree we have to carefully consider what this means if we implement the same semantics in VDM++, and perhaps invariants and so on are relevant. But C++ is allowing this for a good reason, so we should consider what we need carefully too - rather than just assuming Java semantics.

**Comment by peterwvj** [comment]
Thanks for your inputs. One important difference is that the C++ function must be explicitly declared as `virtual` in order to overridden. In that way overriding does not happen by accident as it does in VDM++. But you are right, this is probably not something we should try to solve now. It's more complicated than I thought of to start with.

**Comment by nickbattle** [comment]
Yes, true, this is only for virtual functions. But then in Java, everything is a virtual function. C++ makes a distinction between the cases and provides explicit virtual labelling. I'm not saying that VDM++ should do the same, but we could learn a lot from how C++ has been designed.
