### ISSUE TITLE
Problem with inheritance and overloading of operations

### ISSUE THREAD

**Issue by nickbattle** [overturetool/overture#494]
This is an underlying VDMJ bug (see https://github.com/nickbattle/vdmj/issues/8). Although the type checker limits the inheritance of names when they would overload local definitions (like C++), this limitation is not present in the runtime context, and so the inherited overloads can be executed.

**Comment by peterwvj** [comment]
Was this suppose to be a comment for another issue?

**Comment by nickbattle** [comment]
Now fixed in ncb/development.
