### ISSUE TITLE
Unknown POG crash

### ISSUE THREAD

**Issue by ldcouto** [overturetool/overture#495]
The POG crashes with internal errors on an SL model I've received.

I don't know if the model is public so I'm not placing it here. But I'll update this issue when I've isolated the problem.

Sorry for being so mysterious.

**Comment by nickbattle** [comment]
I had a quick look at this. The failing spec is producing a concurrent modification exception while iterating over the argument list of a mk_ expression inside a TypeCompatibilityObligation. I can't see where the modification is being made, though there is a recursive call to "oneType" from within the loop with the iterator that fails (line 611), so presumably that is somehow changing the list - strange though.

You can reproduce it from the command line (in Eclipse). Just add a breakpoint on Java's ConcurrentModificationException, and run "pog".

**Comment by ldcouto** [comment]
Yeah, I've gotten a bit further than that. It has something to do with type
obligations when passing records to functions.

I'll have a cut down example ready soon.

**Comment by nickbattle** [comment]
Forgot to say, the mk_ expression is on line 146 of the DateTime_v01.vdmsl spec.

It looks like it works if you add a "clone()" at line 667 - though there are several bits of tree building in that same area that also seem to be missing clones.

```
				{
					AIsExp isExp = new AIsExp();
					isExp.setBasicType(ent);
					isExp.setType(new ABooleanBasicType());
					isExp.setTest(exp.clone());     // Was just exp
					po = isExp;
				}
```

**Comment by ldcouto** [comment]
Ok, here is the minimal example:

```
types

A = int
inv a == a>0;
B = nat;

T = B * B *A * B;

functions
f : () -> T
f() ==  let a : int =1,
          nt : T = mk_(0,a,0,0)
         in nt
```

When it emits the PO to ensure that `a` is of type `A`, it crashes.

It's quite bizarre. You need a tuple of size 4 and a function to trigger
the error. At least, I couldn't make it happen any other way.

Anyhoo, I've go this fixed as well. Just need to organise the commits.

Thanks for the help Nick :)
