### ISSUE TITLE
Type checker: unresolved type found in lambda type bind

### ISSUE THREAD

**Issue by peterwvj** [overturetool/overture#496]
If you try to code generate the spec below the code generator finds that there is an unresolved type in the VDM AST. As a consequence the generated code does not compile since unresolved types are represented using `java.lang.Object` (fallback error handling).

~~~
types

N = nat;
      
functions

f :  () -> nat
f () ==
let g = (lambda x : N & x)
in
   g(1);
~~~

The unresolved type is the type of the type bind, i.e. the lambda expression "parameter"
~~~
x:(unresolved DEFAULT`N)
~~~
So I'm guessing that lambda expressions are not type checked correctly

**Comment by nickbattle** [comment]
Yes, it's probably a missing type resolution call. The spec is OK in VDMJ.
```
Parsed 1 module in 0.221 secs. No syntax errors
Type checked 1 module in 0.013 secs. No type errors
Initialized 1 module in 0.03 secs. 
Interpreter started
> p f()
= 1
Executed in 0.028 secs.
```
I'll have a look when I get a minute.

**Comment by peterwvj** [comment]
Thanks. It also appears to be type checking correctly in Overture. The problem only happens when you try to code generate the model. You can even execute it.

~~~
Parsed 1 module in 0.125 secs. No syntax errors
Type checked 1 module in 0.069 secs. No type errors
Initialized 1 module in 0.094 secs. 
Interpreter started
> p f()
= 1
Executed in 0.051 secs. 
~~~

**Comment by ldcouto** [comment]
I've started looking into this. One thing that I find curious is that the error only shows up with user defined types. Lambdas with primitives have correct type info.

Anyway, I just found a FIXME saying "I am not sure if this is the way." in the lambda type check code so I'm looking into that :)

**Comment by nickbattle** [comment]
In the original VDMJ code, it just type resolves the lambda parameters at the start. With this example, it just looks up "unresolved N" and finds the NamedType N. (Haven't looked at Overture).

**Comment by ldcouto** [comment]
Ok, I have found the answer to my first question. The parser sets the lambda types for primitive types. 

Anyway, this is fixed. What I did was type resolve the lambda parameters as part of lambda type checking. This seems to be the general approach in overture. Lets are not resolved at the start either.

@peterwvj , I made some quick experiments with the codegen and it seems to be working, but I'd appreciate it if you could double check (merge with ldc/lambda). Speaking of experiments, what's the easiest way to do a quick invocation of the codegen for test purposes? You don't seem to have a playground :)

**Comment by nickbattle** [comment]
The *parser* was resolving the parameter types?? Strange. The TC ought to be doing it, as you've done, by the sound of it.

**Comment by ldcouto** [comment]
Not resolving *per se*. For primitive types (like `x:nat`), the type field of the `ATypeBind` object was set during the calls to `ExpressionReader`. If it was a user-defined type, the type field would be set as `AUnresolvedType`.

**Comment by nickbattle** [comment]
But the type checker didn't resolve it afterwards?

**Comment by ldcouto** [comment]
It did but it only used it for setting the type of the overall lambda expression. The type bind inside the lambda never got set.

It was actually a fairly simple fix once I found it.

If you want to argue that lambdas should be resolved at an earlier pass, I'm open to the discussion. But on-the-fly resolving is use elsewhere so...

**Comment by nickbattle** [comment]
Oh yes, sure. The type resolving is a mixture of eager (top level definitions) and lazy (deeper types), but it's fine to have the resolve of the parameter types in the TC of the lambda.

**Comment by peterwvj** [comment]
Luis, the easiest way to quickly check the Java code generator output is to invoke it 
`org.overture.codegen.vdm2java.JavaCodeGenMain`

with the arguments
~~~
-sl
/path/to/file.vdmsl
-print
~~~

Usage is:

~~~
Usage: CodeGen <-oo | -sl | -rt | -exp> [<options>] [<files>]
-pp: code generate a VDMPP specification consisting of multiple .vdmpp files
-sl: code generate a VDMSL specification consisting of multiple .vdmsl files
-rt: code generate a limited part of a VDMRT specification consisting of multiple .vdmrt files
-classic: code generate using the VDM classic language release
-vdm10: code generate using the VDM-10 language release
-exp <expression>: code generate a VDMPP expression
-folder <folder path>: a folder containing input vdm source files
-print: print the generated code to the console
-package <java package>:  the output java package of the generated code (e.g. my.code)
-output <folder path>: the output folder of the generated code
-entry <vdm entry point expression>: generate a Java main method based on the specified entry point
-nocodeformat: to NOT format the generated Java code
-junit4: to generate VDMUnit TestCase sub-classes to JUnit4 tests
-separate: to place the code generated model and the test code into separate folders named 'main' and 'test', respectively
~~~

**Comment by peterwvj** [comment]
I'll try your fix Luis and report back

**Comment by peterwvj** [comment]
Yes, this seem to do it. It compiles, runs and everything. Below is the relevant part of the code generator output.

Thanks, for this!
~~~
final public class DEFAULT {
    private DEFAULT() {
    }

    public static Number f() {
        final Func_1<Number, Number> g = new Func_1<Number, Number>() {
                public Number eval(final Number x) {
                    return x;
                }
            };

        return g.eval(1L);
    }

    public String toString() {
        return "DEFAULT{}";
    }
}
~~~

**Comment by ldcouto** [comment]
I think so. I ran all the tests, including externals and everything passed.

*I skipped the random reduction CT tests since I'm on Java 8.*

**Comment by peterwvj** [comment]
Yes, I did run all the tests too and all of them passed. Great.
