### ISSUE TITLE
Clean up the wiki

### ISSUE THREAD

**Issue by ldcouto** [overturetool/overture#500]
I was looking around the wiki for the submodules page...

There is a lot of junk there. I'd like to delete some stuff such as:
* https://github.com/overturetool/overture/wiki/Base-Configuration
* https://github.com/overturetool/overture/wiki/Build-Server
* https://github.com/overturetool/overture/wiki/Contributions
https://github.com/overturetool/overture/wiki/Documentation <--- needs updating if it's kept
* https://github.com/overturetool/overture/wiki/Jenkins-Configuration
* https://github.com/overturetool/overture/wiki/GitHub-Migration
* https://github.com/overturetool/overture/wiki/GitHub-Notifications <-- maybe?

I'll delete all of the above by end of the week, if I hear nothing

**Comment by peterwvj** [comment]
I agree. None of them are useful.

**Comment by ldcouto** [comment]
Done and done.
