### ISSUE TITLE
ValueListenerLists growing due to duplicates

### ISSUE THREAD

**Issue by nickbattle** [overturetool/overture#503]
Internally, invariants and guards monitor changes to the system via ValueListeners, which are added in lists to values that can be changed. But there is a hole somewhere in the management of the lists, such that the lists can acquire duplicate entries and grow indefinitely. This makes updates slower to process and some models which make repeated updates to state can become unacceptably slow or even run out of heap - the shmem model in particular.

This is the same as VDMJ issue #12

**Comment by nickbattle** [comment]
Now fixed in ncb/development.

**Comment by ldcouto** [comment]
How long has this been an issue?

I have a model that gets quite slow but I've always thought it was something in Eclipse.

I'll build a custom version and test this.

**Comment by nickbattle** [comment]
I think I introduced the problem as a side effect of bug #458. It affects models that make repeated updates to the same areas of state data (like the shmem model). These accumulate longer and longer listener lists, which mean that invariants get checked over and over again, making the model slower and slower (but giving correct behaviour).

You could try your model with VDMJ (which has the fix)?
https://github.com/nickbattle/vdmj/releases/download/3.1.1-1/vdmj-3.1.1.jar
