### ISSUE TITLE
Type checker: concrete class gets reported as abstract

### ISSUE THREAD

**Issue by peterwvj** [overturetool/overture#508]
There seems to be a serious problem with type checking of concrete classes which for some situations get recognized as abstract classes. As a consequence the type checker does not allow the class to be instantiated. We have a suspicion that this problem is introduced as a consequence of one of the more recent type checker fixes, but we are not entirely sure. It could be related to #366 

The smallest example we can come up with that produces this problem is shown below.

The error you get is:

~~~
Cannot instantiate abstract class C.
  Unimplemented: m(() ==> ())
  Unimplemented: m(() ==> ())  
~~~

Note that the operation `m` shows up twice.

This does not seem to be a problem with VDMJ. I tried it with the newest version of VDMJ that I built today.

~~~
class A
operations
public m : () ==> ()
m () == is subclass responsibility;
end A

class B is subclass of A
operations
end B

class C is subclass of B
operations

public m : () ==> ()
m () == skip;

end C

class D
values
x = new C(); -- ERROR: C is incorrectly being reported as being an abstract class
end D
~~~

**Comment by nickbattle** [comment]
I'm getting exactly the same error with the latest VDMJ that I have - the real one :)  That's good in a way because it's usually easier to debug. But I'm surprised such a simple example has problems, after that earlier fix.

**Comment by peterwvj** [comment]
Sorry about the confusion. I built VDMJ on `master`. I pointed my terminal to `vdmj/FJ-VDMJ`, executed the `mvn install` and tried the spec with the jar from the `target` folder. Maybe it should have been another branch? Or maybe I screwed up when I copied the binary.

**Comment by nickbattle** [comment]
Well, that should have worked - master is the master :)

I have a fix. It's just three lines, but as usual figuring out how to subsequently fix the test suite is a nightmare. If I send you a patch, could you look at fixing the tests?

**Comment by ldcouto** [comment]
Yup, I'll do it.

(For the record, I am working on improving the test framework. )

**Comment by nickbattle** [comment]
Ah no, it looks like that patch is wrong anyway. The overload-22 tests that fail shouldn't - if you look closely, the overriding member in A3 is defining an operation not a function called "f". I'll have to look more closely at what's failing.

**Comment by nickbattle** [comment]
Hmm. Maybe it is right after all. That overload-22 example causes an error saying that you can't override function "f" with operation "f". Whether or not it goes on to consider the class abstract is perhaps moot - it's "broken" anyway. Can you see whether the patch produces reasonable behaviour from the various tests, and commit if it looks OK?

**Comment by ldcouto** [comment]
I would but I don't have it. Unless you're talking to peter.

**Comment by nickbattle** [comment]
Yes, sorry, emailed the patch to PJ. I'll forward it to you too.

**Comment by peterwvj** [comment]
Sorry for the late reply I was unable to go on Github. Thanks for looking at this. I'll have a look at the patch.

**Comment by ldcouto** [comment]
So, I looked at it. In VDM10, functions are static therefore they cannot be overridden. In fact, abstract static definitions should be banned outright.

In classic this should indeed type-check.

Do we have a mechanism for signalling release version in the TC tests?

**Comment by ldcouto** [comment]
Almost forgot: the overloading of function with an operation...

I dunno if that's legal but I would hope not.

**Comment by peterwvj** [comment]
I think the new error being reported for `overload-22.vpp.result` is reasonable.

Now the `ExternalDemoTest` is also failing due to overload-22.pp spec. I'll probably need to override more test results. I'll give it a look.

**Comment by ldcouto** [comment]
You can disable that test. In fact, disable the entire module. I'll factor
it out soon.

--ldc

**Comment by peterwvj** [comment]
It's not a problem Luis.

So I 1) applied Nick's fix 2) Confirmed that the updates to the result files were OK 3) added a test that uses the spec above and 4) confirmed that it worked on the model that revealed this problem to begin with. I think it's safe to merge. Everything works as expected.

**Comment by ldcouto** [comment]
Kewl! Let's get that RC out.

**Comment by nickbattle** [comment]
OK, glad this is sorted.

@ldcouto Interesting comment about functions being static and therefore "cannot be overridden". I would agree that binding of static methods in languages is usually performed statically (declared type) rather than "virtually", but there is overriding in the sense that methods replace parent class methods, even when the binding  is static. However, in VDM++ (sigh) this normal manner of binding was rejected when we were trying to decide how static functions should be bound. So although functions are always static in VDM10, they are bound virtually, depending on the runtime type of the object reference.

I think it was Shin's idea. I think he couldn't write his famously clever functional specifications in a VDM++ that didn't use virtual binding.

**Comment by ldcouto** [comment]
"Cannot" was the wrong word, I guess. "Should not" would have been better.

Runtime ie dynamic binding of static definitions seems contradictory to me. But I'm sure the LB had good reasons to do it.
