### ISSUE TITLE
Fails to type-check a recursive lambda in values section

### ISSUE THREAD

**Issue by tomooda** [overturetool/overture#516]
The spec below generates "Name 'factorial' is not in scope" error.

```
values
    factorial = lambda x:nat & cases x:
        0 -> 1,
        others -> x * factorial(x-1)
        end
```

**Comment by peterwvj** [comment]
I think you can argue than the error message is sensible since you are referring to a value that is currently being defined. Is your point that forward referencing the value should be allowed because the type infers to a function type (an enhancement).

**Comment by tomooda** [comment]
The related part in the LRM is
<blockquote>
The global values (defined in a value definition) can be referenced at all levels in a VDM
specification. However, in order to be able to execute a specification these values must be
defined before they are used in the sequence of value definitions. This “declaration before
use” principle is only used by the VDM interpreters for value definitions. Thus for instance
functions can be used before they are declared. In standard VDM-SL there are not any
restrictions on the order of the definitions at all.
</blockquote>

So, Peter is right. The interpreter can legitimately reject the spec.
I'll close this issue.
