### ISSUE TITLE
Non-termination when running combinatorial test with module error

### ISSUE THREAD

**Issue by paulch42** [overturetool/overture#532]
Consider the following module:

```
module ct
exports all
definitions 

functions 
  f: nat -> nat
  f(n) == n+1
  post RESULT > 0;

traces
  t_f: f(0);
end ct
```
When run from the Combinatorial Testing view produces the expected result. Now perform the steps:

- in the traces section replace `f` with `f1`
- save the module
- in the CT view select Full Evaluation

The error is not detected by CT. The progress bar appears at the bottom right and permanently shows 0% complete. The only way to terminate the test run is to go to the Progress tab and stop the task.

The CT run can be started multiple times resulting in multiple non-terminating runs that need to be stopped individually from the Progress tab.

CT should check for syntax/type errors in the module and report unable to run to the user.

**Comment by peterwvj** [comment]
Thanks for the very good description.

I changed the traces plugin to check that the model is type correct before running the trace. If the model is not type correct the following message is printed to the trace console:

~~~
<project_name>: Model is not type correct!")
~~~

**Comment by paulch42** [comment]
Thanks for the quick action. That will avoid those unfortunate tasks.
