### ISSUE TITLE
Reading in seq of chars in the CSV library does not work with underscores

### ISSUE THREAD

**Issue by pglvdm** [overturetool/overture#535]
There may be other chars that are not accepted as well but certainly "_" cannot be included right now

**Comment by peterwvj** [comment]
Assuming you have the following CSV data

~~~
1.5,"second",_,1.6
~~~

If you parse the data as shown below

~~~
let mk_(b,xs) = CSV`freadval[seq of ?]("test.txt",1)
in
  for x in xs do ....
~~~

The CSV library tries to parse everything separated by commas as VDM values. When the parser tries to
parse the underscore it complains that the underscore is an unexpected character, which makes sense.

~~~
Error 1009: Unexpected character '_' (code 0x5f) in 'CSV' (console) at line 2:0
~~~

The library signals that the data is invalid (`b` is false in the VDM snippet above). The CSV library never reports the details of parse error.

I'm not sure that this is a bug. What do you think needs to be done?

**Comment by peterwvj** [comment]
A workaround would be to enclose the underscore by string quotes:

~~~
Parsed 3 modules in 0.181 secs. No syntax errors
Type checked 3 modules in 0.122 secs. No type errors
Initialized 3 modules in 0.086 secs. 
Interpreter started
> p A`op()
1.5
second
_
1.6
~~~

**Comment by pglvdm** [comment]
The problem is when you have a string that contains an underscore, i.e. "A12_T6". That is not recognised as a string.

**Comment by peterwvj** [comment]
That works fine on mine - see the following complete example

~~~
module A

imports from CSV all, from IO all
exports all
definitions
operations

op : () ==> ()
op () == 
let mk_(-,xs) = CSV`freadval[seq of ?]("/home/peter/dev/rt-ovt-ws/ImpEx/test.txt",1)
in
  for x in xs do IO`printf("%s\n",[x]);
  
end A
~~~

Output

~~~
**
** Overture Console
**
1
A12_T6
3

A`op() = ()
~~~

Can you show me a small example that demonstrates the problem?

**Comment by pglvdm** [comment]
My mistake. It is also working for me now but if I place:

{["A202","S109","S102","A153"],["A42","A43","A152","A153"],["A42","S114","S102","A153"]}
in a test.text file with a small model like yours:
~~~
module A

imports from CSV all, from IO all
exports all
definitions
operations

op : () ==> bool
op () == 
let mk_(ok,xs) = CSV`freadval[seq of ?]("test.txt",1)
in
  (for x in xs do IO`printf("%s\n",[x]);
   return ok)

end A
~~~
Somehow reading a combination of a set with sequences inside does not work. You get false when you run this.

**Comment by peterwvj** [comment]
I stepped through the `freadval` call and this is what happens:

The tool reads the line

[{["A202", "S109", "S102", "A153"], ["A42", "A43", "A152", "A153"], ["A42", "S114", "S102", "A153"]}]

Then it splits it into tokens separated by comma:

[{["A202",
 "S109",
...
"A153"]}]

Now it tries to construct a VDM value from each of these tokens. Obviously the first token is not a valid value and the parser reports the following error:

~~~
Error 2143: Expecting ']' after list enumeration in 'CSV' (console) at line 2:0
~~~

That's why the sequence being returned is empty and the operation returns `false`

~~~
**
** Overture Console
**

A`op() = false

~~~

The comma separator takes precedence over everything else. I guess this means that CSV data is limited to built-in types. This is a consequence of the data (the tokens) containing commas themselves. I think this is a common assumption to have when parsing CSV data. I'm assuming VDMJ behaves the same.

**Comment by peterwvj** [comment]
@nickbattle Can you confirm?

**Comment by nickbattle** [comment]
VDMJ doesn't have a CSV library.

From what you're saying above, the CSV parse is naively looking for any commas. What I think you would need to do is to call "readExpression()", then check for a comma and loop calling readExpression() if you find a comma. If we don't do something like this, then clearly complex expressions that have nested commas will confuse it. CSV can only really mean "comma separation at the outermost level".

**Comment by peterwvj** [comment]
I think I get what you're saying. Thanks for your input.

**Comment by nickbattle** [comment]
I suppose I'm really saying that we have to define the syntax for the CSV file that we expect to parse, and then write a parser to read it. I think it's something like "<expression> {"," <expression}", where an <expression> is the usual meaning, with a (type check) caveat that it can have no free variables - though interestingly it could have locally bound "let" variables.

**Comment by pglvdm** [comment]
I very much agree with Nick that this is the ideal way to parse such csv files.

**Comment by peterwvj** [comment]
Okay I'm looking into writing a new parser that will do that

**Comment by peterwvj** [comment]
I build a new parser that does what I think we want. Below is a demo. Notice that one of the lines
in the data file has a syntax error, which gets printed. Also note that `let` variables work.

Data:
~~~
true,    'a', 1.5
1,2,3
let a = 1, b = 2 in a + b, 5
{1,2},{3,4}
mk("syntaxerror")
mk_(1,mk_token("cat")), [nil,nil]
{["A202","S109","S102","A153"],["A42","A43","A152","A153"],["A42","S114","S102","A153"]}
~~~

Spec:

~~~
module A

imports from CSV all, from IO all
exports all
definitions
operations

op : () ==> ()
op () == 

let count = CSV`flinecount("test.txt").#2
in 
  for i = 1 to count
  do
    let mk_(ok,xs) = CSV`freadval[seq of ?]("test.txt",i)
    in
    (
     for x in xs do IO`printf("| %s | ",[x]);
     if not ok then
       IO`printf("ERR: %s", [CSV`ferror()]);
     IO`println("\n");
    )

end A
~~~

Output

~~~
**
** Overture Console
**
| true | | a | | 1.5 | 

| 1 | | 2 | | 3 | 

| 3 | | 5 | 

| {1, 2} | | {3, 4} | 

ERR: Error 3182: Name 'mk' is not in scope in 'CSV' (LaunchConfigurationExpression) at line 1:1

| mk_(1, mk_token("cat")) | | [nil, nil] | 

| {["A202", "S109", "S102", "A153"], ["A42", "A43", "A152", "A153"], ["A42", "S114", "S102", "A153"]} | 


A`op() = ()
~~~

**Comment by tomooda** [comment]
Does it allow operation calls?

**Comment by pglvdm** [comment]
wonderful! I don't need operation calls for my work, but I VERY much look forward to be able to use this new CSV implementation!

**Comment by peterwvj** [comment]
It will complain that the operation is not in scope, but it may be possible to do what you are suggesting if the environment is constructed differently. But internally the operation call parses fine. Below is the operation that it uses to convert strings into `Value`s. This was also used by the previous version of the CSV parser.

~~~
private static Value createValue(String module, String method, String value)
    throws Exception
{
  LexTokenReader ltr = new LexTokenReader(value, Dialect.VDM_PP);
  ExpressionReader reader = new ExpressionReader(ltr);
  reader.setCurrentModule(module);
  PExp exp = reader.readExpression();

  Interpreter ip = Interpreter.getInstance();
  ip.typeCheck(exp, ip.getGlobalEnvironment());

  Context ectxt = new Context(ip.getAssistantFactory(), null, method, null);
  ectxt.setThreadState(null, CPUValue.vCPU);
  return exp.apply(VdmRuntime.getExpressionEvaluator(), ectxt);
}
~~~

**Comment by peterwvj** [comment]
So although it would be a neat thing to have it has never been supported.

**Comment by tomooda** [comment]
Peter, no, I'm afraid operation call in CSV could be a flaw. I recommend to keep operation not callable as it is. Sorry for confusion.

**Comment by peterwvj** [comment]
No worries :) it's a good question. I wasn't sure until I tried and I didn't think of it until you asked.

**Comment by nickbattle** [comment]
We did have similar issues with IO`freadval. This also "evaluates" the expression that it reads from the file (but just one in the IO case). So the question is, what context is in scope when it does that? I'd have to check the code for how we did it in the end. But it does affect things like the type-correctness of the expression in the file as well, since the environment may need to include type information from the main spec - for example, can you include "mk_R(1,2,3)"? If so, the type must be in scope, and it may have an invariant that gets called.

Have a quick look at the IO`freadval implementation.
