### ISSUE TITLE
Synchronization issue in TypeComparator

### ISSUE THREAD

**Issue by KasperSaaby** [overturetool/overture#554]
The TypeComparator throws ArrayIndexOutOfBoundsException on line 206 and 568.

**Comment by nickbattle** [comment]
Could you possibly provide the specification that gives this problem, and tell us which version of Overture you are using?

**Comment by KasperSaaby** [comment]
Sorry for the vague description, but my pull request should solve the problem.
If the done vector is static, the synchronization on the public methods should not work.

**Comment by peterwvj** [comment]
Is this related to some of the problems you've experienced when you type check multiple specifications simultaneously? (which the tool does not really support)

**Comment by KasperSaaby** [comment]
Yes, when we are type checking VDM-SL specifications, and not using any synchronization, we are seeing this exception fairly often.

**Comment by peterwvj** [comment]
Okay. Since the tool is designed to do CLI processing, as we discussed, we can't really consider this a bug. Also, there are many other places where we use static fields (type checker errors, warnings etc.) That said, unless there is a good reason for keeping the field static it may be fine to change it to an instance field.

**Comment by peterwvj** [comment]
I'm not sure what impact this change would have. I would like NB to weigh in here since he probably has a better idea about it.

**Comment by KasperSaaby** [comment]
That's okay. I talked with Kenneth about it today, and we saw that the TypeComparator class used to be static. However, the class seems to have been refactored to be non-static. Therefore, we thought that it might have been an oversight, that the vector is still static.

**Comment by peterwvj** [comment]
Okay if the field was left static by accident then we should do something about it.

**Comment by nickbattle** [comment]
This does look like a simple omission when the class was converted from static to non-static. I don't think there is anything more subtle going on, as the "done" field is cleared at the start of the (synchronized) main entry points. Those probably don't need to be synchronized any more either (in a static world have to be - the type comparator is used during some type conversion calculations at runtime, for example).
