### ISSUE TITLE
Toggle Comment Shortcut

### ISSUE THREAD

**Issue by bandurvp** [overturetool/overture#559]
Hi,

I am running Overture for Linux on a laptop with US keyboard layout.  In standard Eclipse I can use Ctrl + / to toggle comments, but this does not work in Overture.  Ctrl + 7 however, does.

**Comment by lausdahl** [comment]
The command is bound at: https://github.com/overturetool/overture/blob/development/ide/ui/plugin.xml#L351

so adding this should fix it: 

```xml
 <key
           commandId="org.overture.ide.ui.commands.toggleComment"
           schemeId="org.eclipse.ui.defaultAcceleratorConfiguration"
            contextId="org.eclipse.ui.textEditorScope"
           sequence="M1+/">
     </key>
```

**Comment by peterwvj** [comment]
Strange I haven't noticed this until now :) Fixed in pvj/main
