### ISSUE TITLE
Suggestion: Bundle Version Control tools with Overture

### ISSUE THREAD

**Issue by ldcouto** [overturetool/overture#564]
There are nice eclipse integrations for Git (http://www.eclipse.org/egit/) and SVN (http://www.eclipse.org/subversive/).

They both work with Overture (I personally use EGit all the time). It would be nice to offer these to our users. We can either pre-install them or just add the update sites to the list that comes preloaded with Overture. It's not a big thing but would be nice, I think.

What do people think?

**Comment by nickbattle** [comment]
Yes, agreed, this would be nice. I've used SVN here at FJ (Subclipse), and presumably EGit would be fine too. It's an important part of the story of "an integrated IDE environment".

**Comment by ldcouto** [comment]
I've never used the SVN integration. Subversive just seemed like the more popular one. But we go with whichever you think is best Nick.

**Comment by peterwvj** [comment]
I'm not sure I like the idea of pre-installing the plugins. It usually adds more context menus, which some user's may find confusing. I'm fine with adding the update sites though.

If we decide to add the update sites we need to update 
`ide/product/src/main/resources/overture.p2.inf`

This usually involves adding two lines to the file. For example, the two lines below add the VDM2C update site

~~~
addRepository(type:0,name:Overture VDM2C Development,enabled:true,location:http${#58}//overture.au.dk/vdm2c/development/ide/repository/target/repository/);\
  addRepository(type:1,name:Overture VDM2C Development,enabled:true,location:http${#58}//overture.au.dk/vdm2c/development/ide/repository/target/repository/);\
~~~

**Comment by peterwvj** [comment]
Do you agree? If so we can add the Subclipse and EGit update sites.

**Comment by nickbattle** [comment]
Yes, happy to just add the update sites.

**Comment by peterwvj** [comment]
Very good. If Luis agrees then I'll try to do that.

**Comment by ldcouto** [comment]
Yeah, I think that is the best solution. Makes it easy to install the plugins but does not force anything.

**Comment by peterwvj** [comment]
Okay. I added the Subclipse and EGit update sites.
