### ISSUE TITLE
Inconsistency when type specified in export list

### ISSUE THREAD

**Issue by paulch42** [overturetool/overture#565]
Consider the following module definition:
```
module A
exports values a:char
definitions 

values 
  a:nat = 1;
end A
```
The definition of `a` and its declaration in the header are inconsistent, but Overture does not report an error. Any import of the module uses the header information so that
```
module B
imports from A all
exports all
definitions 

values 
  b:char = A`a;
end B
```
type checks correctly but if changed to `b:nat = A'a` a compile time type error is reported.
Any attempt to run the version that compiles successfully throws a run time type error.

**Comment by nickbattle** [comment]
Clearly this should catch the export error during type checking. It should be a simple fix.

**Comment by nickbattle** [comment]
OK, this is fixed in VDMJ now - module import and export type checking is much more symmetrical (before it was done differently for each, which wasn't a good idea). I'll get it moved over to Overture when I can, but it will involve some new visitors I think, rather than a simple code port (and I'm about to go away for a week anyway!).

**Comment by nickbattle** [comment]
I think this is now fixed in Overture, ncb/development. The example tests are broken at the moment, but I can never figure out how to update them... :(

**Comment by ldcouto** [comment]
Uh, those have been removed from the build. You should merge with ldc/ntf

**Comment by peterwvj** [comment]
I merged `ncb/development` to get the fix and after that I merged `ldc/ntf` to get the testing related improvements.

**Comment by ldcouto** [comment]
Great. Let me know how it works for you.

**Comment by nickbattle** [comment]
OK, having merged with your stuff Luis, we're all clean.
