### ISSUE TITLE
Type checking fails to identify type error

### ISSUE THREAD

**Issue by paulch42** [overturetool/overture#569]
Consider the following module
```
module x
exports all
definitions 

functions 
  dropWhile[@a]: (@a +> bool) * seq of @a +> seq of @a
  dropWhile(p, s) == cases s:
                       []    -> [],
                       x ^ t -> if p(x) then dropWhile[@a](p, t) else s
                     end
  measure seqlen;

  seqlen[@a]: (@a +> bool) * seq of @a +> nat
  seqlen(-,s) == len s;

end x
```
In the cases expression, the pattern `x ^ t` means both `x` and `t` must be of type `seq of @a`. However, `x` is provided as the argument to `p`, but the argument to `p` must be of type `@a`. The type checker raises no error on this definition.

The pattern should be `[x] ^ t`.

**Comment by nickbattle** [comment]
This is working correctly in the latest 2.3.7 build. I think this problem would have been resolved by the fix to one of your earlier bugs in the same area. You've confirmed that it's also working in the latest VDMJ, so I think we should close this as a duplicate.
