### ISSUE TITLE
Unexpected failure of run configuration

### ISSUE THREAD

**Issue by paulch42** [overturetool/overture#570]
Consider the following module
```
module x
imports from IO all
exports all
definitions 

functions 
  dropWhile[@a]: (@a +> bool) * seq of @a +> seq of @a
  dropWhile(p, s) == cases s:
                       []      -> [],
                       [x] ^ t -> if p(x) then dropWhile[@a](p, t) else s
                     end
  measure seqlen;

  seqlen[@a]: (@a +> bool) * seq of @a +> nat
  seqlen(-,s) == len s;

  less10: nat +> bool
  less10(n) == n < 10;

operations 

  test : () ==> ()
  test() == IO`println(dropWhile[nat](less10, [3,6,9,12,15]));

end x
```
Perform the following steps:
- create project
- create above module
- add IO library
- create a run configuration with function/operation `test()`
- run the configuration

The result is the error message
```
Main 206: Error evaluating code
Detailed Message: Error 3182: Name 'x`test' is not in scope in 'IO' (LaunchConfigurationExpression) at line 1:1
```
The error message would suggest Overture thinks the `IO` module should be aware of the `x` module, when it is the other way round. If run instead as a trace there is no problem.

**Comment by nickbattle** [comment]
This is working for me in the latest 2.3.7 snapshot (and I don't think anything has been changed in the area).
```
**
** Overture Console
**
[12, 15]

x`test() = ()
```
It may have something to do with the alphabetic ordering of the two modules - it is unusual to make module names starting with lower case letters. Can you try renaming it to "X" and see whether that changes the behaviour?

**Comment by nickbattle** [comment]
Just tried in 2.3.6 release, and it's still fine. This is Windows 7, 32-bit Overture. Presumably you're on a Mac, Paul? Can someone else with a Mac try this?

**Comment by peterwvj** [comment]
Mine also chooses the `x` module and executes successfully if I save the launch configuration without specifying a module.

**Comment by peterwvj** [comment]
Paul, can you confirm that the "Module:" text field indeed is empty.

**Comment by paulch42** [comment]
Peter, sorry for the delay in replying. I have 'x' in the 'Module:' field. If I clear the 'Module:' field a red symbol appears beside the 'Main' label on the tab (presumably that indicates an error) and the 'Run' button greys out. From what you say it sounds like your environment somehow automatically selects the module.

I tried changing the module name to 'X' (upper case) but with the same result.

I get this behaviour on both OSX and Windows 10, and on 2.3.6 and 2.3.8.

What I populate on the 'Main' tab is:
- Project set to 'x'
- Launch Mode set to 'Entry Point'
- Module set to 'x'
- Function/Operation set to 'test()'

**Comment by nickbattle** [comment]
Still working for me on 2.3.9-SNAPSHOT, Windows 7.  This is very peculiar.

Do you have any unusual settings on the other launch config tabs: Runtime, Debug, Develop?

**Comment by nickbattle** [comment]
Also, could you ZIP up the entire project folder and send us a copy? It may be that there is something else in there that is causing issues...

**Comment by paulch42** [comment]
Peter, I don’t change any of the settings on any of the other tabs.

Nick, attached is the exported project.

One other piece of information. The “Error Log” tab shows:

eclipse.buildId=unknown
java.version=1.8.0_77
java.vendor=Oracle Corporation
BootLoader constants: OS=macosx, ARCH=x86_64, WS=cocoa, NL=en_US
Framework arguments:  -keyring /Users/paul/.eclipse_keyring -showlocation
Command-line arguments:  -os macosx -ws cocoa -arch x86_64 -keyring /Users/paul/.eclipse_keyring -showlocation

org.overture.ide.debug.core
Error
Sat Jul 09 16:20:20 AEST 2016
internalErrorLoggedFromVdmDebugPlugin206: Error evaluating code
Detailed Message: Error 3182: Name 'x`test' is not in scope in 'IO' (LaunchConfigurationExpression) at line 1:1

org.overture.ide.debug.core.dbgp.exceptions.DbgpDebuggingEngineException: 206: Error evaluating code
Detailed Message: Error 3182: Name 'x`test' is not in scope in 'IO' (LaunchConfigurationExpression) at line 1:1
	at org.overture.ide.debug.core.dbgp.internal.utils.DbgpXmlParser.checkError(DbgpXmlParser.java:150)
	at org.overture.ide.debug.core.dbgp.internal.commands.DbgpDebuggingEngineCommunicator.communicate(DbgpDebuggingEngineCommunicator.java:117)
	at org.overture.ide.debug.core.dbgp.DbgpBaseCommands.communicate(DbgpBaseCommands.java:61)
	at org.overture.ide.debug.core.dbgp.internal.commands.DbgpContinuationCommands.execCommand(DbgpContinuationCommands.java:48)
	at org.overture.ide.debug.core.dbgp.internal.commands.DbgpContinuationCommands.run(DbgpContinuationCommands.java:58)
	at org.overture.ide.debug.core.dbgp.internal.commands.DbgpCoreCommands.run(DbgpCoreCommands.java:166)
	at org.overture.ide.debug.core.model.internal.operations.DbgpResumeOperation.process(DbgpResumeOperation.java:38)
	at org.overture.ide.debug.core.model.internal.operations.DbgpOperation$1.run(DbgpOperation.java:86)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)

**Comment by peterwvj** [comment]
To me it sounds like we are doing the exact same thing :) 

Thanks for the details Paul. I don't see the project attached to the comment. I think it will attach the zip if you drag and drop it onto your comment.

**Comment by peterwvj** [comment]
Just a thought. Can you reproduce the problem using a newly created project that uses a project name that has never been used before in your workspace (to make sure that Overture does not use a folder that was previously created).

**Comment by paulch42** [comment]
[x.zip](https://github.com/overturetool/overture/files/355518/x.zip)

File attached. Tried as you suggested but unfortunately the same result.

**Comment by peterwvj** [comment]
I can finally produce this. The important thing is that all the information must be manually entered in the text fields -- without using dialogs. So enter all the information and click "Run" should produce the problem. By looking at the code I found  out that the dialog used to set the entry points triggers a type check and runs a method that cleverly sets the default modules. These steps are not performed if you enter all the information manually and run the launch config. Therefore, the default module is never set. Obviously we need to make sure that the default module is set for both cases.

**Comment by peterwvj** [comment]
I think I have it fixed now. I built a test version that includes the fix that you can get via the link below. Paul, can you confirm that the fix also works on your machine?

http://overture.au.dk/overture/test/Build-50_2016-07-09_16-02/

**Comment by nickbattle** [comment]
Ah! Good spot PJ.

**Comment by peterwvj** [comment]
Thanks, it was a bit, tricky :D

**Comment by paulch42** [comment]
Thanks Peter, all is good now. I first noticed this issue in a situation with a complex hierarchy of modules but reported it with a simple example. Your fix handles the complex situation as well.

**Comment by peterwvj** [comment]
Very good, Paul. I'm glad it works. I'll close this issue then.
