### ISSUE TITLE
Enable Tempo plotting library feature

### ISSUE THREAD

**Issue by lausdahl** [overturetool/overture#571]
This library enables automated plotting of variables within a model without modifying the model itself.

It is realised as a custom `RemoteControl` class which launched an Electron application which enables the user to select instances starting from the `system` class and adding them to 2 and 3 D plots.

![image](https://cloud.githubusercontent.com/assets/2575418/16260193/933710b2-3866-11e6-803d-6b079939f213.png)

https://www.youtube.com/embed/K7qZr5HCY7g

**Comment by peterwvj** [comment]
This feature is now available via an update site.
