### ISSUE TITLE
Matching file names in two different projects

### ISSUE THREAD

**Issue by ritchje** [overturetool/overture#573]
Version: 2.3.6
Build date: 2016 May 22 17:45 CEST

Hi,

I have two projects that have a matching file name (and module name). When editing one of these, the changes do not apply when saving - the file remains the same as the other one. Overture shows the file correctly but when reopening/or opening in another editor, the file is the same as the other - therefore losing the changes. 

Richie

**Comment by ritchje** [comment]
Deleting the file from one project, also results in the deletion from the other.

**Comment by nickbattle** [comment]
I can't reproduce this, either on 2.3.6 or the new 2.3.8 candidate.

It is possible to create projects in Eclipse that link the same physical file to more than one project. Did you create the two files within Overture, or did you perhaps import them from an existing folder. Such "linked" files show a small arrow on the file icon.

Would it be possible to ZIP up the projects and share them with us?

**Comment by ritchje** [comment]
Apologies, I have since got rid of the two projects. I also just tried to reproduce the problem, but was unable too.

**Comment by peterwvj** [comment]
It is likely that the projects were linked then (as Nick pointed out). Thanks for following up :)
