### ISSUE TITLE
Hexadecimal Values

### ISSUE THREAD

**Issue by ritchje** [overturetool/overture#574]
Overture doesn't seem to recognize hexadecimal values. Please may support be added?

**Comment by nickbattle** [comment]
Now fixed in ncb/development. Not sure why this was omitted from the Overture parser. Small addition.
```
values
	x = 0x10;

> p x
= 16
Executed in 0.034 secs. 
```

**Comment by leouk** [comment]
thanks for this. quick question: are there visible library functions to convert hex to decimal and vice versa (i.e. p x does that!)? We need both hex and these functions and kind of defined them ourselves. Would be nice to have it directly from the tool rather than reinvent them.

**Comment by nickbattle** [comment]
Not that I'm aware of, Leo. The conversion functions should be just a few lines though, surely?

**Comment by leouk** [comment]
well, if you have the values available, yes; we encoded the whole thing by hand (I think with strings or arrays, don't remember) though :-)... So okay when values are fixed.

**Comment by nickbattle** [comment]
Not really sure what you want the functions to do. I meant something like this:
```
values
	hexMap = { x |-> "0123456789ABCDEF"(x+1) | x in set {0, ..., 15} };
	decMap = inverse hexMap;
	
functions
	hex2dec: seq of char -> nat
	hex2dec(hex) ==
		if hex = [] then 0
		else hex2dec(hex(2, ..., len hex)) * 16 + decMap(hex(len hex)) 
	measure m1;
	
	dec2hex: nat -> seq of char
	dec2hex(dec) ==
		if dec = 0 then []
		else dec2hex(dec div 16) ^ [hexMap(dec rem 16)]
	measure m2;
	
	m1: seq of char -> nat
	m1(s) == len s;
	
	m2: nat -> nat
	m2(n) == n;
```
