### ISSUE TITLE
Repository split - disabled artifacts

### ISSUE THREAD

**Issue by lausdahl** [overturetool/overture#577]
The repository has a number of permanently disabled artefacts.

We should either delete them or separate them into their own repo.

An example is:
- tools https://github.com/overturetool/overture/blob/development/pom.xml#L33

**Comment by peterwvj** [comment]
The stuff in the tools folder seems to be garbage files related to an NSI installer and some old version of the example packager. This looks like junk to me. I don't think it's worthwhile moving it to a separate repo.  541b2fb264342a450edcc4c3d4428ae6dd36319e deletes the folder. What other disabled artifacts are you thinking of?
