### ISSUE TITLE
VDM-RT Diagram Export crops figures

### ISSUE THREAD

**Issue by ldcouto** [overturetool/overture#585]
Seems like a max image size issue.

Export:
![vdm-rt-arch](https://cloud.githubusercontent.com/assets/582801/16946790/432b5db0-4da3-11e6-8ce8-38efcf55a41b.jpg)

Screenshot:
![untitled](https://cloud.githubusercontent.com/assets/582801/16946859/acb65e4c-4da3-11e6-8529-43f599b24a46.png)

**Comment by peterwvj** [comment]
The plugin was trying fit the image within a rectangle that was too small. Increasing the offset seems to work.

For a setup consisting of nine CPUs the archiecture is drawn as shown below.

![2016_07_19_18_51_30 rt rtbin arch](https://cloud.githubusercontent.com/assets/5388919/16958717/006b6dd2-4de2-11e6-9fb8-d021904be5ca.jpg)

It also improved the export of some of the other figures.

![2016_07_19_18_51_30 rt rtbin overview](https://cloud.githubusercontent.com/assets/5388919/16958722/03d886a8-4de2-11e6-92b4-d8eca92ed52a.jpg)

**Comment by peterwvj** [comment]
In case it's helpful: the newest test build has the fix http://overture.au.dk/overture/test/Build-59_2016-07-19_19-03/

**Comment by ldcouto** [comment]
Looks good to me. Thanks for the test build.
