### ISSUE TITLE
Overture won't open after update

### ISSUE THREAD

**Issue by richardpayne** [overturetool/overture#588]
I just updated Overture using the Eclipse 'Check for Updates' menu option. Upon completion, I was prompted to restart the application. Overture did not restart and on trying to launch, I get the error "The application “Overture” can’t be opened."  - see screenshot.

![screenshot 2016-08-12 14 27 08](https://cloud.githubusercontent.com/assets/5848867/17623631/e2638094-6098-11e6-9d40-6163192cb570.png)

I believe I had been on v.2.3.0

**Comment by peterwvj** [comment]
Did you try to update *Overture* or did you try to update some other plugin?

Updating Overture using the Eclipse p2 will only work with Overture 2.3.8 once we release Overture (August 31). Base don the information provided I can't tell what went wrong. Does it work if you download a fresh version of Overture (version 2.3.8) and point it to your current workspace?

**Comment by peterwvj** [comment]
No response so I'm closing this issue. Feel free to open it again.
