### ISSUE TITLE
Type checking of dlmodules should be relaxed

### ISSUE THREAD

**Issue by peterwvj** [overturetool/overture#594]
For the module below the error "Exported operation op not defined in module" is reported.

```
dlmodule M
exports

  operations
    op : () ==> ();

  uselib
    "lib.so"

end M
```

This used to type check without errors (I tried it in version 2.3.6) but I suspect that this was changed with one of the recent type checker fixes related to module exports. I talked with PGL about this and he suggests that type checking of dlmodules is relaxed.

**Comment by nickbattle** [comment]
Yes, I must have broken it when fixing the other export problems. I don't think anyone actually uses this - VDMJ does not do external modules this way - but it does allow us to type-check old VDMTools models that include the "dlmodule" feature. I'll have a look.

**Comment by peterwvj** [comment]
Thanks. I'll make sure that the spec above is added as a regression test.

**Comment by nickbattle** [comment]
PJ, I have had a look at this, but I probably won't have time to fix it before 2.4.2. I don't think it's hard, but things are pretty busy here (FJ) at the moment :(

**Comment by peterwvj** [comment]
No worries :) It's not that I needs this feature anyway. I only reported the bug so we don't forget. Thanks for looking into it though.

**Comment by nickbattle** [comment]
This is now fixed in ncb/development.
