### ISSUE TITLE
Problem with function value conversion

### ISSUE THREAD

**Issue by nickbattle** [overturetool/overture#599]
I noticed a small issue. Consider the following:
```
values
	-- Note lambda is nat->int
	f1 : nat -> nat = lambda x:nat & x - 1;		
	f2 : int -> int = lambda x:nat & x - 1;      
```
Overture fails TC with the first value, saying that a nat->int cannot be converted to a nat->nat. The second value passes TC, but when called with f2(-1) produces -2 rather than failing because of the nat parameter to the lambda. I think this second call should fail at runtime.

Incidentally, VDMTools passes TC for both expressions, and fails both at runtime.

**Comment by peterwvj** [comment]
I agree with what you're saying about the second case (`f2`). But what about the first case? I mean, shouln't `f1` type check without errors? Following possible semantics it should be fine since `x-1` could be >= 0. I know it's not entirely the same, but for comparison, the spec below also type checks without errors.

```
values

x : nat = 1 - 2;
```

**Comment by nickbattle** [comment]
Yes, I was thinking about that. You might be right.

**Comment by tomooda** [comment]
I agree with PJ. The ```-``` operator is typed as ```real * real → real``` which is also the type of the ```+``` operator.
```f1``` should be typed without an error by exactly the same reason as ```f3 : nat -> nat = lambda x:nat & x + 1;``` should be typed without an error because ```+``` and ```-``` are of the same type.

**Comment by nickbattle** [comment]
OK, I'll make that tweak too - in fact it wasn't failing TC as such, but failing during initialization when it was trying to create the f1 value (so a runtime assignment error). Without that check, the behaviour is the same as VDMTools.

**Comment by nickbattle** [comment]
Hmm. OK, it is now the same as VDMTools (without the check). But note that both functions will return -1 if called with argument zero, even though the first one is returning a nat. Perhaps we need to consider the domain and range of the assignment separately, and construct a new function value with the widest domain and the narrowest range of the two?

**Comment by tomooda** [comment]
I don't think the assignment should raise a runtime type error.
The error should be reported when ```f(0)``` returns -1.

The static type of ```f1``` is ```nat -> nat```. ```f(0)``` is hence statically typed as ```nat```. When ```f(0)``` evaluates to non-nat value, it should cause a runtime type error.

**Comment by tomooda** [comment]
And yes, nick, constructing a function typed ```nat -> nat``` that wraps the lambda function ```nat->real``` will do the job.
(I found I should update CG of ViennaTalk in that way ;-P)

**Comment by nickbattle** [comment]
It looks like what I need is a function with tha narrowest domain/range of the two. Doing that gives us the following:
```
> p f1(0)
Error 4065: Value -1 is not a nat in 'DEFAULT' (console) at line 1:1
> p f2(0)
= -1
> p f1(-1)
Error 4065: Value -1 is not a nat in 'DEFAULT' (console) at line 1:1
> p f2(-1)
Error 4065: Value -1 is not a nat in 'DEFAULT' (console) at line 1:1
```
And no type checking errors. This looks right to me, agreed? The only one that works is passing a nat to the int->int f2.

**Comment by tomooda** [comment]
The results look reasonable. But, what if we have ```values f4 : int -> int = f1;```?
Should ```f4(0)``` evaluates to ```-1```, or results in an error?
To me, the former looks natural.

**Comment by nickbattle** [comment]
With what I've just committed, your f4(0) case fails, because f1 has been trimmed down to nat->nat, and it won't widen that again in the assignment to f4. But I agree it's a debatable point. VDMTools produces -1.

**Comment by tomooda** [comment]
I think your fix is enough for now.
If we want to unify those behaviors as a part of the language spec, I'd rather propose to add a return type declaration into the lambda expression. 😄

**Comment by nickbattle** [comment]
Yes, good point. Making lambdas explicit might help a lot here. Perhaps a future RM though :)
