### ISSUE TITLE
The welcome page does not work after self-update

### ISSUE THREAD

**Issue by lausdahl** [overturetool/overture#603]
After a self-update overture shows the popup after the restart:

![image](https://cloud.githubusercontent.com/assets/2575418/19073804/48b11488-8a3d-11e6-805f-b5af9fc4e578.png)

I tested updating from 2.4.0 to a newer snapshot version

**Comment by peterwvj** [comment]
We looked into this some time ago. We follow a standard/recommended approach to setting up the welcome page. It's likely that this is a problem with Eclipse. The good thing is that this bug does not break any tool features and I believe it is unlikely that users will try to update Overture while the welcome page is opens.
