### ISSUE TITLE
Isagen tasks

### ISSUE THREAD

**Issue by CThuleHansen** [overturetool/overture#615]
- [ ] Isa: How are VDM-SL values created and initialized?
- [ ] Isa: Union types e.g. `ut = nat | int;`
- [ ] Isa: Quote types e.g. `Qualification = <Elec> | <Mech> | <Bio> | <Chem>;`
- [ ] Isa: How are functions / operations invoked?
- [ ] Isa: Return value of functions / operations
- [x] Isa: card operator
- [ ] Isa: inds operator
- [ ] Isa: For all and there exists operator for multiple variables e.g.  
`forall x,y : nat such that...`
`forall x: nat, y: int such that ...`
- [ ] Isagen: Missing test for there exists

**Comment by nickbattle** [comment]
@CThuleHansen Can you explain what this issue is for? I'm trying to clean up open Overture issues that we don't need.

**Comment by CThuleHansen** [comment]
@nickbattle this is really outdated, and Jamie has done a lot of work since. A new issue should be created if needed. Closing it.
