### ISSUE TITLE
discrepancy between VDMJ and Overture outputs

### ISSUE THREAD

**Issue by leouk** [overturetool/overture#616]
In an example like

Record1 :: 
	x: nat
        y: nat

Record2 = Record1
inv mk_Record2(x,y) == x > y

VDMJ (correctly?) states that mk_ for Record2 is not possible, whereas Overture allows the behaviour. In this simple case where Record1 doesn't have invariants it's okay. But in complex cases with recursive invariants this way Overture treats the situation could lead to hard-to-spot loops for the user.

I would say the stricter view of VDMJ is nicer.

Best,
Leo

**Comment by nickbattle** [comment]
Record2 is not a record type, in this example. You cannot say mk_Record2(1,2) for example. So similarly, the mk_Record2 pattern in the invariant should always be a type error.

**Comment by leouk** [comment]
Indeed. But Overture does not flag it as an error. It accepts mk_Record2 as a pattern. 
Interestingly, it does not accept it anywhere else but the invariant constraint! Everywhere else, it says Record2 is not a valid/known record type, yet at inv it allows (at ought not to).

**Comment by nickbattle** [comment]
The code was checking whether the mk_ type was a record fundamentally (which it is) when it should have been testing whether it is a tagged type (which it isn't). One line fix :)

I've pushed the change to ncb/development.
