### ISSUE TITLE
AccountSys VDM Class

### ISSUE THREAD

**Issue by matin1978** [overturetool/overture#620]
Hello,
I want to work with an example of VDM-SL with the name "AccountSys" that I downloaded from overture web site, but, I can not find VDM Class for running the example. Does anyone know what should I do and where can I download this Class?

**Comment by shinsahara** [comment]
Hi matin,

This model is not a VDM++ model, so there is no Class.
And the AccountSys model is an implicit model, so you can’t execute this model.

If you want to run this model, you have to modify this model to an explicit model.
In explicit model, all functions and operations have to have function’s body or operations body.

For example, you should modify the addAccount operation as following:

 addAccount(numberIn: AccNum, detailsIn: Details, limitIn: real)  == (
 	accounts := accounts munion {numberIn |-> mk_Account(numberIn, detailsIn, 0, limitIn,[])};
 	skip -- just for debugging
 )
 ext wr accounts: map AccNum to Account
 pre numberIn not in set dom accounts and limitIn >= 0
 post accounts = accounts~ munion {numberIn |-> mk_Account(numberIn, detailsIn, 0, limitIn,[])};

This syntax of operation is called “extended explicit operation definition.”

And you can debug this operation in Overture Tools as following:



Cheers,
Shin

-----------------------------------------------------------------------
Imagine the World Movement!
Shin Sahara
E-Mail: ss @ shinsahara.jp <http://shinsahara.jp/>    shinsahara @ gmail.com <mailto:shinsahara@gmail.com>   http://shinsahara.j <http://shinsahara.com/>p
Mobile:  +81-80-3089-7518(in the world)
------------------------------------------------------------------------

**Comment by matin1978** [comment]
Hello
Thank you for your answer. I will try it and let you know about results. 
Best kinds
Mo.

**Comment by nickbattle** [comment]
Mo, this isn't really a bug, so I think we should close this issue. We'd be happy to discuss any problems you have using Overture on the Users email list: overture-users@overturetool.org
