### ISSUE TITLE
Recursion between type with invariant and a value using it gives strange error message

### ISSUE THREAD

**Issue by pglvdm** [overturetool/overture#626]
With a VDM-SL model such as
~~~
module A

definitions

types

  Digit = char
  inv c == c in set DIGIT;

values

  DIGITS:seq of Digit = "0123456789";
  DIGIT:set of char = elems DIGITS;

functions

Test: nat -> nat
Test(n) == n
end A
~~~
If one tries to debug "A`Test(42)" one gets an error message like:
~~~
Error 4034: Name 'A`DIGIT' not in scope in 'A' (/Users/pgl/Documents/Overture/workspaceNew/Test/A.vdmsl) at line 8:21
Error 4034: Name 'A`DIGITS' not in scope in 'A' (/Users/pgl/Documents/Overture/workspaceNew/Test/A.vdmsl) at line 13:29
Initialization: Error 4034: Name 'A`DIGIT' not in scope in 'A' (/Users/pgl/Documents/Overture/workspaceNew/Test/A.vdmsl) at line 8:21
~~~
I can understand why it is hard because there is essentially a mutual recursion here, but at least if we cannot cope with it I think that we should be able to give a better error message.

**Comment by nickbattle** [comment]
I agree that this is probably the most unhelpful and confusing aspect of VDMJ, and it is often difficult to see what exactly is wrong. Unfortunately "fixing it" isn't trivial. I have looked at it in the past, but given up :) What it really needs is a cycling dependency check in the type checker; there may also need to be a weaker test for forward references, though I think that's less of an issue.

I'll give it another look.

It is beside the point, but VDMTools (Linux 9.0.7) gives roughly the same error at init:
```
test.vdm, l. 8, c. 21:
  Run-Time Error 74: Unknown identifier
    value: "DIGIT"
```

**Comment by nickbattle** [comment]
I'm taking another look at this. I've added some cyclic dependency checking to the VDMJ type checker, but it still needs a lot of testing - I'm worried that bugs will prevent valid specifications from initializing! At the moment, the specification in the original post is producing the following:
```
Parsed 1 module in 0.109 secs. No syntax errors
Error 9999: Cyclic dependency detected in 'A' (test.vdm) at line 13:3
Cycle: [A`DIGIT, A`DIGITS, A`DIGIT]
Error 9999: Cyclic dependency detected in 'A' (test.vdm) at line 12:3
Cycle: [A`DIGITS, A`DIGIT, A`DIGITS]
Warning 5000: Definition 'Test' not used in 'A' (test.vdm) at line 17:1
Type checked 1 module in 0.238 secs. Found 2 type errors and 1 warning
Bye
```
This is correct, but it would be more helpful if it should show that the dependency from DIGITS to DIGIT is actually via the invariant of the Digit type. I'll see if that's possible.

**Comment by nickbattle** [comment]
OK, tweaked it slightly. Now it's reporting the Digit name explicitly in the cycles:
```
Error 9999: Cyclic dependency detected in 'A' (test.vdm) at line 13:3
Cycle: [A`DIGIT, A`DIGITS, Digit, A`DIGIT]
Error 9999: Cyclic dependency detected in 'A' (test.vdm) at line 12:3
Cycle: [A`DIGITS, Digit, A`DIGIT, A`DIGITS]
Error 9999: Cyclic dependency detected in 'A' (test.vdm) at line 7:3
Cycle: [A`Digit, A`DIGIT, A`DIGITS, A`Digit]
```

**Comment by nickbattle** [comment]
I've pushed an Overture version of this enhancement to ncb/development. It should be tested carefully before being included in the main release because any problems would prevent otherwise legitimate specifications from starting. (To help with this, setting the property "skip.cyclic.check" will prevent the checks)

**Comment by nickbattle** [comment]
Note that the current version does not consider the initialization of instance variables using (hopefully pure) operations. It only covers "functional" initialization - ie. constant values and their initialization via functions and other values (though this includes the implicit functions that are formed via state/type invariants). It should be possible to extend the cycle detection to operations/statements, though it is harder to detect when code is conditional (and we have to know this to avoid false positives). Cyclic dependency detection is something that we can enhance over time; it should still be useful, even if it is not catching every possible cycle.

**Comment by nickbattle** [comment]
This can be closed now?

**Comment by peterwvj** [comment]
Yes, I'm OK with that.
