### ISSUE TITLE
Record Value cannot be created for Aliased Record Type

### ISSUE THREAD

**Issue by f-ishikawa** [overturetool/overture#634]
When I make a type definition as an alias to an existing record type, it is not possible to make a value of the aliasing type by mk_XXX.

See the following simple sample.

```
types
RecordTypeA ::
  x : int
  y : nat;

RecordTypeARef = RecordTypeA;

operations
test : () ==> RecordTypeARef
test() ==
  return mk_RecordTypeARef(3, 3); -- ERROR: "RecordTypeARef is not a record type"
```

I found this issue when my student used an alias like this in a test module to refer to the type definition in the test-target module (so that she does not need to attach the module name every time like ModuleA`RecordTypeA). The above sample might look meaningless to have an alias in the same module but in the original situation making an alias to a record type was useful.

**Comment by nickbattle** [comment]
I believe this is correct functionality. I remember deliberately changing it - earlier versions of VDMJ/Overture would have permitted this.

See https://github.com/overturetool/overture/issues/616 and https://github.com/overturetool/overture/issues/244.
