### ISSUE TITLE
File AlarmInitUML.uml

### ISSUE THREAD

**Issue by m3lter** [overturetool/overture#646]
Hi,

I am not able to find UML file mentioned in chapter "3.3 Using Modelio"
of the document "Tutorial for Overture/VDM++".

**Comment by nickbattle** [comment]
Hi, I've attached the file below (renamed as *.txt for GitHub!). Where were you looking for the file?

[AlarmInitUML.uml.txt](https://github.com/overturetool/overture/files/1308982/AlarmInitUML.uml.txt)

**Comment by peterwvj** [comment]
I'll consider this issue close. Feel free to raise this issue in the [documentation repository](https://github.com/overturetool/documentation).
