### ISSUE TITLE
** operator type errors have wrong location information

### ISSUE THREAD

**Issue by peterwvj** [overturetool/overture#649]
This issue can easily be demonstrated by type-checking the following class.  The *actual* and *expected* error locations are marked using comments.

```
class A

operations

public static op : () ==> nat
op () ==
let a = 2,
    b = '2' -- Error reported here
      
in
  return a ** b; -- Expected error to be reported here

end A
```

VDMJ has the same problem.

**Comment by nickbattle** [comment]
OK, I'll take a look. It's usually a trivial thing, using the location of a definition rather than the location of an expression that uses that definition.

**Comment by peterwvj** [comment]
Yeah, that's what I thought. Thanks!

**Comment by nickbattle** [comment]
OK, fix now in ncb/development. As expected, just the wrong object's location being used.

**Comment by peterwvj** [comment]
Sounds good, thanks Nick!
