### ISSUE TITLE
PO for Cash Dispenser example in VDM-SL contains "null"

### ISSUE THREAD

**Issue by pglvdm** [overturetool/overture#651]
If one imports the standard CashDispenserSL example and run the proof obligation generation the fifth PO states:
(forall date:DEFAULT`Date, ts:seq of (DEFAULT`Transaction) & is_(Sum([(t.amount) | null & ((t.date) = date)]), nat))
the "ı null" part seem to be a mistake to me.

**Comment by peterwvj** [comment]
What is the expected PO?

**Comment by pglvdm** [comment]
Actually I don't think that this PO is necessary at all since it should always be of the right type as far as I can see. But it would probably be a good idea also to try this example in VDMTools as well.

**Comment by tomooda** [comment]
Because ```Sum``` is typed ```seq of real +> real```, I think we need a proof of that Sum([xs]) always returns a value of ```nat``` on the assumption that all members of xs are nat. It's a trivial induction, but anyway I think it's good to have a proof of it.
I tried the nightly build of VDMTools, but couldn't get it run with the CashDispenser example, BTW.

**Comment by pglvdm** [comment]
Oh yes, Tomo is right. I agree with that.

**Comment by nickbattle** [comment]
It looks like we didn't update the PO generator when we added "in seq" bindings. Any simple PO that includes them produces the "null" PO. For example:
```
	f: seq of real +> seq of nat
	f(s) ==
		[t | t in seq s];

PO: (forall s:seq of (real) & is_([t | null], seq of (nat)))
```
Should be easy to find...

**Comment by nickbattle** [comment]
VDMJ works, you'll be pleased to hear:
```
f: subtype obligation in 'DEFAULT' (TestSL.vdmsl) at line 2:5
(forall s:seq of (real) &
  is_([t | t in seq s], seq of (nat)))
```

**Comment by nickbattle** [comment]
It was actually a problem with the toString AST configuration for seq binds.
Fix now in ncb/development.
