### ISSUE TITLE
Type-checker: ord clause crashes type-checker

### ISSUE THREAD

**Issue by peterwvj** [overturetool/overture#655]
### Description

Overture fails to type-check an `ord` clause.

### Steps to Reproduce

1. Create a file `Dates.vdmpp` with the following content

```
class Dates
	types

  Date :: year : nat
          month: nat1
          day  : nat
  ord mk_Date(y1,m1,d1) < mk_Date(y2,m2,d2) == true;

end Dates
```

2. Type-check that file using `java -jar Overture-2.5.4.jar -vdmpp Dates.vdmpp `

**Expected behavior:**
The model should type-check without errors.

**Actual behavior:** [What actually happens]

Overture crashes with the following output:

```bash
λ java -jar Overture-2.5.4.jar -vdmpp Dates.vdmpp 
Parsed 1 class in 0.036 secs. No syntax errors
java.lang.NullPointerException
Type checked 1 class in 0.046 secs. Found 1 type error
```

**Reproduces how often:** [What percentage of the time does it reproduce?]

Every time.

### Versions

- Overture version 2.5.4, the command-line interface.
- Ubuntu 17.04
- openjdk version "1.8.0_151" 64 bit

### Additional Information

This error was identified by @nina-j

**Comment by nickbattle** [comment]
OK, I can reproduce this, so it should be fixable - the problem is VDM++ specific (it's fine in SL) and it's also fine in VDMJ. It's something to do with there being no "self" pointer for the function created when the ord_T function is built - this is null, where is should point to the class definition containing the type.

**Comment by nickbattle** [comment]
OK, I see the problem. It's essentially as I said above. The type checking code that builds the min/max functions for the type was missing the setting of the class definition pointer. Adding that then allows the spec to check cleanly.

I'll run the tests, then check in to ncb/development.
