### ISSUE TITLE
Sequence Enumeration

### ISSUE THREAD

**Issue by ritchje** [overturetool/overture#661]
### Description

Sequence enumeration does not work.

### Steps to Reproduce

`[1,...,10] = Error 2034: Unexpected token in expression: ... in 'DEFAULT' (console) at line 1:4`

### Versions

Version: 2.5.2
Build date: 2017 Sep 11 10:27 CEST
Git commit description: Release/2.5.2.

**Comment by peterwvj** [comment]
Ranges currently only works for sets:

```
{1,...,10} = {1, 2, 3, 4, 5, 6, 7, 8, 9, 10}
```
I think what you want to achieve is:

```
[i | i in set{1,...,10}] = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
```

So it's not a bug.

Does that help?

**Comment by peterwvj** [comment]
If order is imporant, you could define a function like this:

```
functions
seqRange: int * int -> seq of int
seqRange(f,t) ==
if f > t then []
else
  [f] ^ seqRange(f+1,t);
```

**Comment by nickbattle** [comment]
PJ is right, there is no such thing as a sequence range. But I've often wondered why not, given that set ranges exist. They would be very useful sometimes.

You could submit a request for a language extension to the Language Board? But it would take a while to get approved/implemented.

**Comment by ritchje** [comment]
@peterwvj @nickbattle Page 63 of the VDM manual mentions sequence enumeration? Maybe I've misinterpreted it?

**Comment by peterwvj** [comment]
Sequence enumerations are just sequence constructors, e.g. `{1,2,3}` so it's not a range
