### ISSUE TITLE
The Class/function selection in launch configurations is not sorted making it difficult to find a class

### ISSUE THREAD

**Issue by lausdahl** [overturetool/overture#665]
### Description
The class/function selection in a launch configuration is not sorted. This makes it difficult to locate a specific class when a model contains a large number of classes. 
![image](https://user-images.githubusercontent.com/2575418/36392938-e1f78c42-15ad-11e8-9955-d44c4a13d75c.png)

**Expected behavior:** A sorted list + optionally the ability to search by pattern matching

**Actual behavior:** Unsorted list is presented

**Reproduces how often:** always

### Versions

Overture Platform

Version: 2.5.6
Build date: 2017 Dec 11 09:50 CET
Git commit description: Release/2.5.6

**Comment by peterwvj** [comment]
I agree that the names should be sorted alphabetically.

Searching you can already do. Just click a class name and start typing. But you are right, it does not support pattern matching, e.g. `*` and stuff like that.

**Comment by peterwvj** [comment]
`AbstractVdmMainLaunchConfigurationTab.chooseOperation` is a good starting point.

**Comment by peterwvj** [comment]
@lausdahl Added alphabetic sorting of class names. Check the development build when this build job has finished

https://build.overture.au.dk/jenkins/job/overture-development/190/ 

Does it work as expected?
