### ISSUE TITLE
Precedence inconsistency between code and documentation

### ISSUE THREAD

**Issue by sifraser** [overturetool/overture#682]
### Description
The VDM language reference (Appendix C) states that:

>  The precedence ordering on the families is:
>        *combinators > applicators > evaluators > relations > connectives > constructors*

However Overture uses the following precedence ordering:
*applicators > combinators > evaluators > relations > connectives > constructors*

### Steps to Reproduce
Given the following:
```
functions

function1: nat -> nat
function1(n) == is not yet specified;
function2: nat -> nat
function2(n) == is not yet specified;
 
iterate1: nat * nat1 -> nat
iterate1(n, x) == (function1 ** x)(n);
  
iterate2: nat * nat1 -> nat
iterate2(n, x) == function1 ** x(n);
 
comp1: nat -> nat
comp1(n) == (function1 comp function2)(n);
 
comp2: nat -> nat
comp2(n) == function1 comp function2(n);
```

Then, both iterate2 and comp2 fail type checking as the applicator is given a high precedence than the combinator during parsing.

This was discussed on the Overture Users mailing list and it was felt that this was correct, but the documentation should be updated to reflect this.

### Versions
Applies to 2.6.2

### Additional Information
See also https://github.com/overturetool/overture/issues/141

**Comment by nickbattle** [comment]
I think this has been dealt with by issue #141, which is now closed.
