### ISSUE TITLE
Operator precedence

### ISSUE THREAD

**Issue by ivor-spence** [overturetool/overture#702]
### Description

Order of evaluation of multiple relations is right to left. I am not sure if this is deliberate - the language definition seems to ignore this possibility.

### Steps to Reproduce

In the quick interpreter type

print 3 = 3 = true

**Expected behavior:** [What you expect to happen]

A response of "true"

**Actual behavior:** [What actually happens]

Error 3087: Left and right of '=' are incompatible types in 'DEFAULT' (console) at line 1:3

However print true = 3 = 3 gives "true". The right hand "=" is evaluated first.

**Reproduces how often:** [What percentage of the time does it reproduce?]

Every time

### Versions

Version 2.5.4 on Windows

### Additional Information

So A = B = C is treated as A = (B = C)
whereas 4 - 2 - 2 is treated as (4 - 2) - 2

**Comment by nickbattle** [comment]
Interesting observation :)  I would normally call this operator associativity, but the Language Ref Manual calls it "Grouping", and it is defined in section C.7.

The "=" operator is in the family "Relations" and C.7 states that there is "No grouping". In C.4 it says, "Typing dictates that there is no meaningful way of using them adjacently."  Yet your example is clearly a meaningful way, when comparing booleans. Evidently the parser chooses right grouping in this case (it has to group somehow, but I'm not sure this is wrong).

The "-" operator (your other example) is in the family "Evaluators" and these are stated to have left grouping, which your example confirms.

I tried your two "=" examples in the VDMTools command line, but both of them give an error. VDMTools has left grouping for the "-" operator.

So I'm not sure whether this is a problem or not. Any other views on this?

**Comment by ivor-spence** [comment]
Nick,

Thanks for your response, it’s clearly not a major issue. As you say the problem is really that there is no stated grouping for relations, in fact there is a statement that none is needed,  where clearly there is a need. I suppose I thought it would have been more consistent for it to group to the left.

I am using the software to teach some discrete maths to first year students and am trying to emphasise that there are clear rules which need to be followed as instinct can lead us astray. My favourite example is

false and false = false and false

which (correctly but counter-intuitively) evaluates to false.

So as long as I them that relations group to the right I suppose that’s ok.

Another thing missing in the language definition I think is that exponentiation (**) is not listed in any operator family although I would expect it to be an Evaluator. It groups to the right in Overture, which is the standard mathematical interpretation. E.g. 2**2**3 = 2**(2**3).

Sorry for reporting this as a bug but I was trying to be sure that I understood what was happening.

Best wishes,

Ivor

**Comment by nickbattle** [comment]
We're always perfectly happy to have problems reported, even if they really just need more clarification in the Language Ref Manual!

Exponentiation is curious, I agree: it's treated the same as the "iterator" operator for maps and functions, which is therefore in the Combinators family and has right-associativity. It would intuitively belong in the Evaluators (and so be left-associated), but ... it's not.

I'll raise both issues in the Language Board with a view to making things clearer in the LRM.

**Comment by ivor-spence** [comment]
Nick,

Raising it with the Language Board would be good but I would suggest that the current right-associativity for exponentiation is actually what it should be, even if this has been a happy accident in the language. I think the mathematical convention is

[cid:image001.png@01D579E2.34DDAB50]

**Comment by tomooda** [comment]
Hi,

Just FYI.
I checked VDMTools and ViennaTalk, and the both parse the ** operator
right-associative likewise to VDMJ/Overture.

Best Regards,
---
tomo

2019年10月3日(木) 20:01 ivor-spence <notifications@github.com>:

**Comment by nickbattle** [comment]
The issue was raised at the LB meeting today and a suggestion has been made for additional explanation to add to section C.7 about grouping.

**Comment by nickbattle** [comment]
The LRM change has now been made, and will be included in the next release. Closing.
