### ISSUE TITLE
Dialect preference shows vdm10 and errors are issued as it was checked against the classic dialect 

### ISSUE THREAD

**Issue by idhugoid** [overturetool/overture#715]
Import VDM-SL projects and error appears...

**Comment by idhugoid** [comment]
Apparently the preferences set vdm10 in Overture GUI are correctly transmitted to VDMJ... Either the error message problem is inside VDMJ or maybe non-existent at all. Can I close this issue @nickbattle or do you think there may be some classic vdm error message issued by VDMJ even if -r vdm10 is passed as a parameter that is worth pursuing inside VMDJ?

**Comment by nickbattle** [comment]
Hmm... well obviously there should be no classic tests that fail if -vdm10 is set. But without a specific example, it's hard to fix. It says "import the projects", but it would be better to get one specific example of the error. Is that possible?
