### ISSUE TITLE
Map operation fails with "Error 4089: Can't get real value of map"

### ISSUE THREAD

**Issue by f-ishikawa** [overturetool/overture#724]
### Description

The domain restriction operation for a map fails with an error.

### Steps to Reproduce

Using 2.7.4, the following operations lead to
Error 4089: Can't get real value of map in 'Test2'

> public test1a : () ==> ()
> test1a() == (
>   dcl m : map token to int := { mk_token(1) |-> 1 };
>   m := {mk_token(1)} <:- m;
> );
> 

> public test1b : () ==> ()
> test1b() == (
>   dcl m : map int to int := { 1 |-> 2 };
>  m := {1} <:- m;
> );

**Comment by nickbattle** [comment]
Thanks for reporting this. There is definitely something strange here, but the domain restriction operator is `<-:` rather than `<:-`. If you change that, it appears to work correctly(?). So I need to look at why or how `<:-` parses without an error. I'll investigate.

**Comment by nickbattle** [comment]
So `setval <:- mapval` parses as `setval <: (-mapval)`. But for some reason, the type check of a unary minus is not checking that the argument is numeric. So for example `-"Hello"` does not cause a type checking error (it causes a runtime error, of course).

So in your case, it was trying to "cast" a map to a numeric value, which in the general case is `real`. Hence the error, cannot get real value of map.

The fix looks relatively simple. Just checking it now.

**Comment by nickbattle** [comment]
Now fixed in ncb/development.
