### ISSUE TITLE
17 tests failing

### ISSUE THREAD

**Issue by idhugoid** [overturetool/overture#733]
org.overture.typechecker.tests.external.ExternalClassesRtTypeCheckTest.test[extension-13.vpp]
    org.overture.typechecker.tests.external.ExternalClassesRtTypeCheckTest.test[extension-12.vpp]
    org.overture.typechecker.tests.external.ExternalClassesRtTypeCheckTest.test[extension-01.vpp]
    org.overture.typechecker.tests.external.ExternalModulesSlTypeCheckTest.test[letexpr-23.vdm]
    org.overture.core.testing.samples.SampleExternalsTest.testCase[63 : extension-13.vpp]
    org.overture.core.testing.samples.SampleExternalsTest.testCase[64 : extension-12.vpp]
    org.overture.core.testing.samples.SampleExternalsTest.testCase[65 : extension-01.vpp]
    org.overture.core.testing.samples.SampleExternalsTest.testCase[1494 : letexpr-23.vdm]
    org.overture.core.testing.samples.SampleExternalsTest.testCase[2365 : extension-13.vpp]
    org.overture.core.testing.samples.SampleExternalsTest.testCase[2366 : extension-12.vpp]
    org.overture.core.testing.samples.SampleExternalsTest.testCase[2367 : extension-01.vpp]
    org.overture.core.testing.samples.SampleExternalsTest.testCase[3157 : modules-01.vdm]
    org.overture.core.testing.samples.SampleExternalsTest.testCase[3158 : modules-06.vdm]
    org.overture.core.testing.samples.SampleExternalsTest.testCase[3159 : modules-04.vdm]
    org.overture.core.testing.samples.SampleExternalsTest.testCase[3160 : modules-05.vdm]
    org.overture.core.testing.samples.SampleExternalsTest.testCase[3161 : modules-03.vdm]
    org.overture.core.testing.samples.SampleExternalsTest.testCase[3162 : modules-02.vdm]

**Comment by nickbattle** [comment]
Several of the changes would have produced changes in the expected results of these tests, but the expected results are included in the tree, so they should have been included with the merges. Can you expand one of the errors?

**Comment by idhugoid** [comment]
Hi Nick, here is one of the expansions:

[Input: /var/lib/jenkins/internal-resources/externaltests/tc/rttest/VICE/extension/extension-13.vpp, Result:src/test/resources/external/tc/rttest/VICE/extension/extension-13.vpp.result, Update Property:testing.update.testing.standard.SampleExternalsTest.extension-13.vpp] Expected (but not found) Strings: 
Error 3294: extension-13.vpp at 41:8 Only one system class permitted
Error 3427: extension-13.vpp at 7:10 Unable to resolve type name 'CPU'
Error 3427: extension-13.vpp at 12:10 Unable to resolve type name 'CPU'
Error 3427: extension-13.vpp at 17:10 Unable to resolve type name 'CPU'
Error 3427: extension-13.vpp at 20:10 Unable to resolve type name 'BUS'
Error 3427: extension-13.vpp at 47:13 Unable to resolve type name 'CPU'
Error 3427: extension-13.vpp at 52:13 Unable to resolve type name 'CPU'
Error 3427: extension-13.vpp at 57:13 Unable to resolve type name 'CPU'
Error 3133: extension-13.vpp at 7:17 Class name CPU not in scope
Error 3428: extension-13.vpp at 7:10 Unable to resolve type name 'CPU'
Error 3134: extension-13.vpp at 45:36 Class has no constructor with these parameter types
Error 3133: extension-13.vpp at 47:20 Class name CPU not in scope
Error 3428: extension-13.vpp at 47:13 Unable to resolve type name 'CPU'
Error 3428: extension-13.vpp at 7:10 Unable to resolve type name 'CPU'
Error 3428: extension-13.vpp at 47:13 Unable to resolve type name 'CPU'
Error 3209: extension-13.vpp at 91:14 Member HandleEvent(nat) is not in scope
Error 3209: extension-13.vpp at 92:14 Member HandleEvent(nat) is not in scope
Error 3209: extension-13.vpp at 93:14 Member HandleEvent(nat) is not in scope
Found (but not expected) Strings: 
Error 2295: extension-13.vpp at 141:13 Name contains a reserved prefix
Error 2295: extension-13.vpp at 161:28 Name contains a reserved prefix

**Comment by nickbattle** [comment]
Ah!  The clue is at the end, where it says that the name contains a reserved prefix. That change was made a while back, and therefore included changes to the *external* tests branch as well as the main development branch. I remember being careful to point this out to you at the time :-)  So it looks like this has not been merged into the branch of external tests that you are testing with.  For example, like 141 should now read:
```
  protected mx_stimuli : nat := 0;
```
This used to be "max_stimuli", which is an illegal name.

See https://github.com/overturetool/overture/issues/711, which says, "NOTE that the external test suite has also changed slightly to remove the accidental error cases. This is also in a branch called ncb/development of the https://github.com/overturetool/externaltests repository."

**Comment by idhugoid** [comment]
Thanks. I will look into how this works...

**Comment by idhugoid** [comment]
External tests needed to be updated in the build server. Back to passing!
