### ISSUE TITLE
java error

### ISSUE THREAD

**Issue by ghost** [overturetool/overture#784]
Hey everyone its my first time to download overture i downloaded java se dev kit 8 and this error keeps popping up
any help?:(
[](url)
![ov](https://user-images.githubusercontent.com/65318419/132136926-7b78daf5-547d-40a4-b79d-3b9caa982ef3.png)

**Comment by nickbattle** [comment]
This is most likely because you're using a 32-bit version of Java with a 64-bit version of Overture. It looks like this is the case, since the Java executable is in "Program Files (x86)". Can you try uninstalling this and installing a 64-bit Java?

**Comment by ghost** [comment]
Thank you so much its working now!
